### ISSUE TITLE
Cronjob running every minute causes memory leak

### ISSUE THREAD

**Issue by peterhell95** [openshift/okd#1104]
**Describe the bug**
When we run the cronjob which run every 1 minutes, the memory utilisation increase by 0,5-1% every day. This Cronjob scheduled in the separated node. For example worker01.example.node.
Our fear is that if Cronjob ran every 10 or 15 minutes, memory utilisation would still increase, but obviously not to the same extent.

**Version**
4.9.0-0.okd-2022-01-14-230113

**How reproducible**
Cronjob.yaml:
```yaml
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: memleak-test-job
  namespace: cronjob-test
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: hello
              image: 'busybox:latest'
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          nodeName: worker01.example.node
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
```

  
**Log bundle**
n/a
