### ISSUE TITLE
oc new-app cannot set environment variables for CronJob batch/v1

### ISSUE THREAD

**Issue by douggutaby** [openshift/okd#1178]
**Describe the bug**
oc new-app --env-file or -e parameter is not working for CronJob batch/v1

**Version**
From 4.8.0

**How reproducible**
If the apiversion in the template file is batch/v1beta1 for cronjob and use oc new-app --env-file, the generated yaml with dry-run will contain the environment variables.
If I do the same with batch/v1, the generated file won't have environment variables.

The server version is 4.8.0 and I tried with clients 4.8.0-4.10.0
4.7.0 client cannot handle batch/v1 for CronJob so it is ok to not working.

**Comment by JaimeMagiera** [comment]
Confirmed for the following as well. 

Client Version: 4.9.0-0.okd-2022-02-12-140851
Server Version: 4.9.0-0.okd-2022-02-12-140851
Kubernetes Version: v1.22.1-1839+b93fd35dd03051-dirty

➜  testing oc new-app -f cron-template.yaml -e foo=bar --dry-run -o yaml
```
apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: cron-template
      app.kubernetes.io/component: cron-template
      app.kubernetes.io/instance: cron-template
    name: pi
  spec:
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
            labels:
              parent: cronjobpi
          spec:
            containers:
            - command:
              - perl
              - -Mbignum=bpi
              - -wle
              - print bpi(2000)
              env:
              - name: foo
                value: bar
              image: perl
              name: pi
              resources: {}
            restartPolicy: OnFailure
    schedule: '*/1 * * * *'
    startingDeadlineSeconds: 200
    successfulJobsHistoryLimit: 3
    suspend: true
  status: {}
kind: List
metadata: {}
```
➜  testing oc new-app -f cron-template.yaml -e foo=bar --dry-run -o yaml
```
apiVersion: v1
items:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: cron-template
      app.kubernetes.io/component: cron-template
      app.kubernetes.io/instance: cron-template
    name: pi
  spec:
    concurrencyPolicy: Replace
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
            labels:
              parent: cronjobpi
          spec:
            containers:
            - command:
              - perl
              - -Mbignum=bpi
              - -wle
              - print bpi(2000)
              image: perl
              name: pi
              resources: {}
            restartPolicy: OnFailure
    schedule: '*/1 * * * *'
    startingDeadlineSeconds: 200
    successfulJobsHistoryLimit: 3
    suspend: true
  status: {}
kind: List
metadata: {}

```
