### ISSUE TITLE
oVirt: Request: make ovirt guest agent available

### ISSUE THREAD

**Issue by abaxo** [openshift/okd#126]
Hi,

At the moment it doesn't appear that the oVirt guest agent runs on OKD nodes. It would be desirable for things like memory ballooning and network statistics to run this in the same way that we would run open-vm-tools for vSphere.

[oVirt guest agent docs](https://www.ovirt.org/documentation/vmm-guide/chap-Installing_Linux_Virtual_Machines.html)

**Comment by vrutkovs** [comment]
That can be done, sure. Do you know if there's an RPM (and a service) which provides it?

**Comment by abaxo** [comment]
I *think* so. In the docs they list this RPM as being available for EL: `ovirt-engine-guest-agent-common` 
Services are:
``` 
ovirt-guest-agent.service
qemu-guest-agent.service
```

There is also an atomic system container, I dont know if that will be useful or not for FCOS:
```
 # atomic pull --storage=ostree ovirtguestagent/centos7-atomic
     # atomic install --system --system-package=no --name=ovirt-guest-agent ovirtguestagent/centos7-atomic
     # systemctl status ovirt-guest-agent
     # systemctl start ovirt-guest-agent
```

**Comment by vrutkovs** [comment]
Oh, if it can be containerized then its a preferable way really. I wonder if @rgolangh has plans for this (we might need an openshift extension for that)

**Comment by rgolangh** [comment]
When the container is consumable (will be under registry.redhat.com) I'll add a machine-config object, to make it a static container on all of the nodes
https://bugzilla.redhat.com/show_bug.cgi?id=1764804

**Comment by vrutkovs** [comment]
Isn't it already released as https://access.redhat.com/containers/#/registry.access.redhat.com/rhev4/ovirt-guest-agent?

**Comment by abaxo** [comment]
I don't know how to add a machine-config object, but FWIW I have the agent running as a daemonset:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ovirt-guest-agent
  namespace: openshift-ovirt-infra
spec:
  selector:
    matchLabels:
      app: ovirt-guest-agent
  template:
    metadata:
      labels:
        app: ovirt-guest-agent
    spec:
      volumes:
        - name: virtio-ports
          hostPath:
            path: /dev/virtio-ports
            type: ''
      containers:
        - name: ovirt-guest-agent
          image: registry.access.redhat.com/rhev4/ovirt-guest-agent
          resources: {}
          volumeMounts:
            - name: virtio-ports
              mountPath: /dev/virtio-ports
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
```
