### ISSUE TITLE
csi-snapshot-controller-operator don`t have rights to read configmaps in kube-system

### ISSUE THREAD

**Issue by msheldyakov** [openshift/okd#131]
Pod openshift-csi-snapshot-controller-operator/csi-snapshot-controller-operator-78569d7cfc-rfm5b (operator) is restarting

logs from csi-snapshot-controller-operator-78569d7cfc-rfm5b:
 1 cmd.go:120] unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:openshift-csi-snapshot-controller-operator:csi-snapshot-controller-operator" cannot get resource "configmaps" in API group "" in the namespace "kube-system"

**Comment by vrutkovs** [comment]
We're gonna need release image and must-gather archive to debug that

**Comment by msheldyakov** [comment]
Release image:  registry.svc.ci.openshift.org/origin/release:4.4.0-0.okd-2020-04-07-111354
(quay release, then upgrade).
Must-gather: https://drive.google.com/open?id=13rCMT89liCdOFzVLLZXz400A6_fTb3rP

I can try to reproduce on clean cluster with specified version.
+Found a mention of an error in the e2e test logs https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-okd-installer-e2e-aws-upgrade/13

**Comment by msheldyakov** [comment]
logs from openshift-csi-snapshot-controller-operator/csi-snapshot-controller-operator-xx:
`W0408 13:40:53.248689       1 authentication.go:348] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'`

Operator use sa openshift-csi-snapshot-controller-operator:**csi-snapshot-controller-operator**
But i found cluster role for sa csi-snapshot-controller-operator:**openshift-cluster-storage-operator**
Manual creating a role for the correct sa corrects errors.

Original:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-snapshot-controller-operator-role
subjects:
  - kind: ServiceAccount
    name: csi-snapshot-controller-operator
    namespace: openshift-cluster-storage-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```

Fixed
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-csi-snapshot-controller-operator-role
subjects:
  - kind: ServiceAccount
    name: csi-snapshot-controller-operator
    namespace: openshift-csi-snapshot-controller-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
