### ISSUE TITLE
OKD support for VMware provider

### ISSUE THREAD

**Issue by DanyC97** [openshift/okd#14]
We would like to keep this master issue to link new issues which are related to VMware deployment so we can keep track as well as letting community know if a specific provider deployment is supported or has known issues etc

**Comment by klzsysy** [comment]
install failure:

refer doc
  - https://blog.openshift.com/openshift-4-2-vsphere-install-quickstart/
  - https://docs.openshift.com/container-platform/4.2/installing/installing_vsphere/installing-vsphere.html#installing-vsphere

vsphere 6.7u3
dhcp server readyed
   - pool `10.30.40.0/24`


install config 
```yaml
apiVersion: v1
## The base domain of the cluster. All DNS records will be sub-domains of this base and will also include the cluster name.
baseDomain: ifaii.lo
compute:
- name: worker
  replicas: 1
controlPlane:
  name: master
  replicas: 3
metadata:
  ## The name for the cluster
  name: openshift4
networking:
  clusterNetworks:
  - cidr: 172.31.0.0/22
    hostPrefix: 25
  machineCIDR: 10.30.40.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.31.128.0/22
platform:
  vsphere:
    ## The hostname or IP address of the vCenter
    vcenter: vcenter.ifaii.lo
    ## The name of the user for accessing the vCenter
    username: administrator@vsphere.local
    ## The password associated with the user
    password: xxxx
    ## The datacenter in the vCenter
    datacenter: home
    ## The default datastore to use.
    defaultDatastore: NVME-SSD
## The pull secret that provides components in the cluster access to images for OpenShift components.
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"xxxx","email":"xxx@gmail.com"},"quay.io":{"auth":"xxxx","email":"xxx@gmail.com"}}}'

## The default SSH key that will be programmed for `core` user.
sshKey: "ssh-rsa AAAABxxxxxx sonny@Sonny.macmini"
```

use [OVA](https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/latest/rhcos-4.2.0-x86_64-vmware.ova)

append-bootstrap.ign
> refer #19 set  append-bootstrap.ign from 2.x.x to 3.0.0 invalid
```json
{
  "ignition": {
    "config": {
      "append": [
        {
          "source": "http://172.30.10.14:8080/bootstrap.ign",
          "verification": {}
        }
      ]
    },
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {}
}
```
bootstrap vm config

![image](https://user-images.githubusercontent.com/3226923/69916675-df2bde00-1498-11ea-8c30-377501f77dc7.png)

vcenter folder
![image](https://user-images.githubusercontent.com/3226923/69916731-acceb080-1499-11ea-82b0-1160dd558c3c.png)

result:

bootstrap screen:
stuck this
![image](https://user-images.githubusercontent.com/3226923/69916667-b9063e00-1498-11ea-81c4-f7a5a5ec0f44.png)

http server status

![image](https://user-images.githubusercontent.com/3226923/69916776-31213380-149a-11ea-82c1-1cbebf08771d.png)
