### ISSUE TITLE
OKD 4.4 Single Node Cluster: Install will not complete until prometheus-k8s is scaled to one replica

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#163]
OKD Release: 4.4.0-0.okd-2020-04-21-163702

When building a single node cluster, the installation will be stuck waiting on `monitoring` to complete.  It is waiting on the second `prometheus-k8s` pod to start.

You can force completion by scaling down the Prometheus CRD:

```
oc patch Prometheus k8s --type merge --patch '{"spec":{"replicas":1}}'
```

The installation will complete, however, the monitoring operator will undo the change to the CRD and scale it back up to two replicas.

**Comment by vrutkovs** [comment]
Why would the second replica not start? It has antiaffinity rule to run on different nodes, but if there is none available it would run both on the same node.

In order to start with 1 replica cluster-monitoring-operator has to support this - but this proposal has been [rejected](https://github.com/openshift/cluster-monitoring-operator/issues/715). The patch to scale down prometheus instances to 1 cannot be applied by installer (bootstrap won't complete), so this action has to be done post installation manually

**Comment by cgruver** [comment]
I wonder if it's something about how the affinity rule is written?  `preferredDuringSchedulingIgnoredDuringExecution`

When you scale it down and then back up, it does successfully deploy both replicas on the single master node.  Before that, it complains that it can't find a node to schedule on.


```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: prometheus
                      operator: In
                      values:
                        - k8s
                namespaces:
                  - openshift-monitoring
                topologyKey: kubernetes.io/hostname
```
