### ISSUE TITLE
OKD 4.5 IPI on vSphere fails

### ISSUE THREAD

**Issue by slaterx** [openshift/okd#199]
**Describe the bug**
Attempting to install OKD 4.5 IPI on vmware doesn't complete. Bootstrap and 3 masters are successfully created, API responds but the remaining infrastructure elements are not created. The 3 masters keep writing on Journal that no pods can be scheduled since /etc/kubernetes/cni/net.d contains no CNI config. `oc adm must-gather` is unavailable since there's no api to authenticate. 

Here's the install-config.yaml:
```yaml
apiVersion: v1
baseDomain: okd4.home.lab
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:{}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: test-ipi
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 192.168.13.25
    cluster: aiur
    datacenter: gnhq
    defaultDatastore: datastore_CRIO_pool_raid5
    ingressVIP: 192.168.13.26
    network: Private
    password: ...
    username: ...
    vCenter: vcenter.internal.home.lab
publish: External
pullSecret: {"auths":{"fake":{"auth":"bar"}}}
sshKey: ssh-rsa AAAA....
```

**Version**
OKD 4.5 IPI over vCenter 6.7U3 (quay.io/vrutkovs/okd-release:4.5-dev, installer image - quay.io/vrutkovs/okd-installer@sha256:c7ccad0839a44f4dd993e19ba4b23b5158df1d1951c4f0584daff64d6911660a)

**How reproducible**
100% - Attempted 5 times until all logs collected.

**Log bundle**
Archive URL: https://keybase.pub/slaterx/okd4/ovnkubernetes.tar.gz

Archive content:
- openshift-install.log
- output of `openshift-install create cluster --log-level debug`
- `journalctl` from bootstrap and masters
