### ISSUE TITLE
OKD4.4 - Install fails on OpenStack with self-signed certs

### ISSUE THREAD

**Issue by behnm** [openshift/okd#223]
I need to install okd4.4-beta4 on openstack (VIO 5.1 vmware integrated openstack). However, when I try to install okd4.4 on openstack by IPI, I see the below error. 

**FATAL failed to fetch Install Config: failed to fetch dependency of "Install Config": failed to fetch dependency of "Base Domain": failed to generate asset "Platform": Post https://x.x.x.x:5000/v3/auth/tokens: x509: certificate signed by unknown authority**

I use this link and do step by step.
https://docs.openshift.com/container-platform/4.4/installing/installing_openstack/installing-openstack-user.html

**Comment by ashaver** [comment]
Can confirm duplication on daily 4.5.0-0.okd-2020-05-21-094504. I will go get logs.

**Comment by ashaver** [comment]
[log-bundle-20200621200614.tar.gz](https://github.com/openshift/okd/files/4810566/log-bundle-20200621200614.tar.gz)

**Comment by vrutkovs** [comment]
@ashaver I don't think you're hitting the same issue: CVO object has desired version `4.5.0-0.okd-2020-06-21-094504`, but CVO logs on master 192.168.57.50 has `Desired version from operator is v1.Update{Version:"4.4.0-0.okd-2020-05-23-055148-beta5"`.

Seem you've joined the master which is already running 4.4-beta5 and didn't get provisioned again?

**Comment by ashaver** [comment]
Absolutely correct. My teardown script was not resetting the disk on the VM.

**Comment by behnm** [comment]
Excuse me. I've not got your answers. 
martin andre in below link said: "The team considers this bug as valid. "
https://bugzilla.redhat.com/show_bug.cgi?id=1786314

**Comment by bshephar** [comment]
Hi, so to confirm. Does your clouds.yaml look similar to this?

```
[stack@undercloud-0 openstack]$ cat clouds.yaml-backup 
clouds:
  openshift:
    auth:
      auth_url: https://172.20.10.25:13000
      password: iIyO3W4zKMfGpkrgaSsfx8a4N
      project_domain_name: Default
      project_name: openshift
      user_domain_name: Default
      username: admin
    identity_api_version: '3'
    region_name: regionOne
    cacert: "/etc/pki/ca-trust/source/anchors/ca.crt.pem"

```

With the `cacert:` param specified?  In my case, I'm deploying OCP from my TripleO Director node and it does indeed trust that CA. 

If it is in your clouds.yaml file, are you also able to add it to your systems trusts like so:
```
cp ca.crt /etc/pki/ca-trust/source/anchors
sudo update-ca-trust extract
```
(I'm assuming you have the ca.crt file somewhere and are able to copy it)

Do you still get the same error after doing that?
