### ISSUE TITLE
envFrom not working in Lifecycle hooks

### ISSUE THREAD

**Issue by lomholdt** [openshift/okd#228]
**Describe the bug**
When creating a lifecycle hook using the Recreate deploy strategy and a `envFrom` is used in the `execNewPod` hook type, the values are not picked up when the hook pod is deployed.

**Version**
oc v3.10.127
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://openshift
openshift v3.11.188
kubernetes v1.11.0+d4cacc0

**How reproducible**
100% - the `envFrom` is not picked up at all.

**Log bundle**
N/A

```yaml
    strategy:
      type: Recreate
      recreateParams:
        mid:
          failurePolicy: Abort
          execNewPod:
            command:
            - /bin/sh
            - '-c'
            - >-
              cd /app &&
              /usr/bin/dotnet Test.dll arg1
            containerName: Test
            env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            envFrom:
              - secretRef:
                name: TestSecret
            volumes:
              - data
```
