### ISSUE TITLE
Explicitly enable redhat-operators when using a pull secret containing redhat.registry.io

### ISSUE THREAD

**Issue by cloudbustinguk** [openshift/okd#247]
**When using an 'official' pull secret, non-community redhat operators should also be enabled**

Official pull secret (those containing registry.redhat.io) installations of OKD go on to enable only the community-operators:

```
apiVersion: config.openshift.io/v1
kind: OperatorHub
...
spec:
  disableAllDefaultSources: true
  sources:
  - disabled: false
    name: community-operators
status:
  sources:
  - disabled: true
    name: redhat-operators
    status: Success
```
This change was introduced in [26a139d097a2](https://github.com/openshift/installer/commit/26a139d097a2964fc6f88cb3740c0921a4275cb6)

**Resolution**

Explicitly enable the redhat-operators:

```bash
[dsw@box]$ (cat <<EOF
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  disableAllDefaultSources: true
  sources:
  - disabled: false
    name: redhat-operators
  - disabled: false
    name: community-operators
EOF
 ) | oc apply -f -
operatorhub.config.openshift.io/cluster configured
[dsw@box]$
``` 

**Version**

4.5.0-0.okd-2020-06-29-110348-beta6

**How reproducible**

100% reproducible, as:

```
disableAllDefaultSources: true
```
.. is set, and the cluster install uses a manifest which only explicitly enables the community-operators.

**Log bundle**

N/A
