### ISSUE TITLE
Documentation missing for All-in-one OKD 4

### ISSUE THREAD

**Issue by mangelajo** [openshift/okd#250]
**Describe the bug**
The documentation for OKD 4 doesn't explain how to deploy an all in one deployment. We were planning to use something like that in the CI pipeline of the submariner project http://github.com/submariner-io to reduce the cost of deploying a fully fledged OKD 4

**Version**
OKD 4 documentation

**How reproducible**
N/A

**Log bundle**
N/A

**Comment by vrutkovs** [comment]
It should be as simple as setting 
```
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
```
in `install-config.yaml`, but the docs should also mention that the host cannot be modified via MCO - and the cluster cannot be updated
