### ISSUE TITLE
OCP 4.4 baremetal installation failed with error "no matches for kind MachineConfig" repeatedly

### ISSUE THREAD

**Issue by realmjian** [openshift/okd#267]
**Describe the bug**
When installed OCP 4.4 with baremetal installation method, after "bootstrap" node up and running, got following errors repeatly without "Machine Config Operator" started, until 24 hours reached and x509 expired,still the same problem.

```
Jul 17 11:58:18 bootstrap.ocp44.ibmcrl.com bootkube.sh[76991]: "99_openshift-machineconfig_99-master-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-master-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
Jul 17 11:58:18 bootstrap.ocp44.ibmcrl.com bootkube.sh[76991]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
```

**Version**
UPI installation method

tried version: Openshift 4.4.12, 4.4.11, 4.4.5

**How reproducible**

**Log bundle**
[log-bundle-20200717183148.tar.gz](https://github.com/openshift/okd/files/4937658/log-bundle-20200717183148.tar.gz)

** install-config.yaml **

```
apiVersion: v1
baseDomain: mytest.com
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: ocp44
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":......}' 
sshKey: 'ssh-rsa ......'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
 ......
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.ocp44.mytest.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.ocp44.mytest.com:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
```

Thanks !
