### ISSUE TITLE
OKD 4.5.0-0.okd-2020-07-29-070316 installation failing on oVirt 4.3.10

### ISSUE THREAD

**Issue by nevenr** [openshift/okd#287]
**Describe the bug**
After master hosts creation they get IPs from DHCP server (confirmed via DHCP server logs) and for some time they are reachable (we can ping them). After a while they become unreachable. API VIP address newer become reachable. 
After 20min openshift-install fail.

**Version**
OKD: 4.5.0-0.okd-2020-07-29-070316
IPI: oVirt 4.3.10

**How reproducible**
Every time (100% rate).
install-config.yaml:
```
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  .......
  -----END CERTIFICATE-----
apiVersion: v1
baseDomain: nt.lan
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
imageContentSources:
- mirrors:
  - cir.nt.lan:443/origin
  source: quay.io/openshift/okd-content
- mirrors:
  - cir.nt.lan:443/origin
  source: registry.svc.ci.openshift.org/origin/release
metadata:
  creationTimestamp: null
  name: tara
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.52.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  ovirt:
    api_vip: 10.0.51.6
    dns_vip: 10.0.51.5
    ingress_vip: 10.0.51.7
    ovirt_cluster_id: xxxxxxxxxx
    ovirt_network_name: OpenShift
    ovirt_storage_domain_id: yyyyyyyyyyyyyyyyyyyyy
    vnicProfileID: zzzzzzzzzzzzzzzzzz
publish: External
pullSecret: '{ .... }'
sshKey: |
  ssh-rsa A......
```
ovirt-config.yaml:
```
ovirt_url: https://ovme.nt.lan/ovirt-engine/api
ovirt_username: user@internal
ovirt_password: xxxxxxxxxxx
ovirt_insecure: true
ovirt_ca_bundle: |-
  -----BEGIN CERTIFICATE-----
  ......
  -----END CERTIFICATE-----
```

**Log bundle**
```
Apply complete! Resources: 5 added, 0 changed, 0 destroyed.
OpenShift Installer 4.5.0-0.okd-2020-07-29-070316
Built from commit 699277bb61706731d687b9e40700ebf4630b0851
Waiting up to 20m0s for the Kubernetes API at https://api.tara.nt.lan:6443...
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Still waiting for the Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get https://api.tara.nt.lan:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp 10.0.52.6:6443: connect: no route to host
Fetching Bootstrap SSH Key Pair...
Loading Bootstrap SSH Key Pair...
Using Bootstrap SSH Key Pair loaded from state file
Reusing previously-fetched Bootstrap SSH Key Pair
Fetching Install Config...
Loading Install Config...
  Loading SSH Key...
  Loading Base Domain...
    Loading Platform...
  Loading Cluster Name...
    Loading Base Domain...
    Loading Platform...
  Loading Pull Secret...
  Loading Platform...
Using Install Config loaded from state file
Reusing previously-fetched Install Config
Pulling debug logs from the bootstrap machine
Added /home/nt/.ssh/id_rsa to installer's internal agent
Added /tmp/bootstrap-ssh110021374 to installer's internal agent
Attempted to gather debug logs after installation failure: failed to create SSH client, ensure the private key is added to your authentication agent (ssh-agent) or specified with the --key parameter: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Bootstrap failed to complete: failed waiting for Kubernetes API: Get https://api.tara.nt.lan:6443/version?timeout=32s: dial tcp 10.0.52.6:6443: connect: no route to host
```
