### ISSUE TITLE
OKD 4.5 Failed to install on OpenStack using IPI: internal addresses are expected to be 192.x

### ISSUE THREAD

**Issue by ITD27M01** [openshift/okd#293]
**Describe the bug**

Hi Guys.

We are trying to deploy OKD 4.5 cluster on OpenStack and it isn't successful:
```
oc get clusteroperator 
NAME                                       VERSION                            AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                                                                Unknown     Unknown       True       46m
cloud-credential                                                              True        False         False      50m
cluster-autoscaler                                                                                                 
config-operator                                                                                                    
console                                                                                                            
csi-snapshot-controller                                                                                            
dns                                        4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      44m
etcd                                       4.5.0-0.okd-2020-07-14-153706-ga   False       True          True       46m
image-registry                                                                                                     
ingress                                                                                                            
insights                                                                                                           
kube-apiserver                                                                False       True          True       46m
kube-controller-manager                                                       False       True          True       46m
kube-scheduler                             4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      44m
kube-storage-version-migrator              4.5.0-0.okd-2020-07-14-153706-ga   False       False         False      46m
machine-api                                                                                                        
machine-approver                                                                                                   
machine-config                                                                False       True          True       46m
marketplace                                                                                                        
monitoring                                                                                                         
network                                    4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      46m
node-tuning                                4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      46m
openshift-apiserver                        4.5.0-0.okd-2020-07-14-153706-ga   False       False         False      46m
openshift-controller-manager                                                  False       True          False      46m
openshift-samples                                                                                                  
operator-lifecycle-manager                 4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      45m
operator-lifecycle-manager-catalog         4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      45m
operator-lifecycle-manager-packageserver                                      False       True          False      45m
service-ca                                 4.5.0-0.okd-2020-07-14-153706-ga   True        False         False      46m
storage                                                                                                            
```

Maybe this can help:
```
 oc logs machine-config-operator-6889c8c64-g4smf -n openshift-machine-config-operator | tail -n5
I0810 11:36:23.142949       1 sync.go:62] [init mode] synced RenderConfig in 10.763155ms
I0810 11:36:43.746862       1 sync.go:62] [init mode] synced RenderConfig in 30.267614ms
I0810 11:37:24.799481       1 sync.go:62] [init mode] synced RenderConfig in 13.42165ms
I0810 11:37:39.004023       1 sync.go:62] [init mode] synced RenderConfig in 12.527877ms
E0810 11:37:39.049417       1 operator.go:331] openshift-config-managed/kube-cloud-config configmap is required on platform OpenStack but not found: configmap "kube-cloud-config" not found
```
**Version**

4.5.0-0.okd-2020-07-14-153706-ga/4.5.0-0.okd-2020-07-29-070316
32.20200629.3 Fedora CoreOS
**How reproducible**

reproducible 100%
```
cat install-config.yaml

apiVersion: v1
baseDomain: cloud.example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    openstack:
      type: k.medium
      rootVolume:
        size: 100
        type: standard
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    openstack:
      type: k.medium
      rootVolume:
        size: 100
        type: standard
  replicas: 3
metadata:
  creationTimestamp: null
  name: rtc-kit
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.100.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 10.30.0.0/16
platform:
  openstack:
    apiVIP: 10.100.0.5
    cloud: openstack
    clusterOSImage: fedora-coreos-32.20200629.3.0-openstack.x86_64
    computeFlavor: k.medium
    externalDNS:
     - 172.30.0.14
     - 173.30.0.15
    externalNetwork: public
    ingressVIP: 10.100.0.7
    lbFloatingIP: 172.18.102.240
    octaviaSupport: "1"
    trunkSupport: "1"

openshift-install create cluster
```
**Log bundle**

http://igortiunov.ru/log-bundle-20200810142816.tar.gz

**Comment by ITD27M01** [comment]
```
oc get cm -n openshift-config-managed                                                                                   
NAME                                  DATA   AGE
bound-sa-token-signing-certs          1      9m30s
console-config                        1      12m
csr-controller-ca                     1      9m36s
kube-apiserver-aggregator-client-ca   1      9m43s
kube-apiserver-client-ca              1      8m30s
kube-apiserver-server-ca              1      8m19s
kubelet-bootstrap-kubeconfig          1      12m
kubelet-serving-ca                    1      9m10s
sa-token-signing-certs                1      12m
service-ca                            1      9m38s
signatures-managed                    0      7m14s
trusted-ca-bundle                     1      11m
```

**Comment by vrutkovs** [comment]
Nodes report `rtc-kit-jt65m-master-0.net.billing.ru`, but mDNS expects `rtc-kit-jt65m-master-2.rtc-kit.cloud.nexign.com`. Seems `baseDomain` and DHCP are misaligned?

**Comment by ITD27M01** [comment]
Hi @vrutkovs 
Yes, there some misaligned because of OpenStack limitations for search suffixes management.

I don't think it is a core issue because the OpenShift cluster works well on the same infra. If I understand it correctly the network or machine operator configures search suffix for machines. And there is resolv.conf from OpenShift 4.5 cluster:

```
[core@rtc-lxjpt-master-1 ~]$ cat /etc/resolv.conf 
# Generated by OpenStack resolv prepender NM dispatcher script
search rtc.cloud.nexign.com
nameserver 10.100.0.6
nameserver 172.30.0.14
nameserver 172.30.0.15
```

Maybe fcos have another logic for this and I of course will check this.

**Comment by vrutkovs** [comment]
search suffixes are coming from DHCP - its not clear though why nodes are a) not reporting as FQDN, b) have `billing.ru` suffix in the hostname (what are the outputs of `hostname` and `hostname -f`?)

**Comment by ITD27M01** [comment]
Because of IPI there is no any DNS registration for nodes. Is it required?

Again, in OpenShift I see the following:
```
[core@rtc-lxjpt-master-1 ~]$ hostname
rtc-lxjpt-master-1.net.billing.ru
[core@rtc-lxjpt-master-1 ~]$ hostname -f
rtc-lxjpt-master-1.net.billing.ru
```

For FCOS I can do the following:

```
guestfish add $IMAGE_FILE : \
          run : \
          mount "$fs_boot_path" / : \
          mkdir /coreos-firstboot-network : \
          copy-in "ens3.nmconnection" /coreos-firstboot-network/ : \
          chmod 0600 /coreos-firstboot-network/ens3.nmconnection : \
          unmount-all : \
          exit
```
Where ens3.nmconnection looks like:
```
[connection]
id=ens3
uuid=0c85d1ee-87a7-4a10-b5b9-776f3462ad6d
interface-name=ens3
type=802-3-ethernet
autoconnect=true
autoconnect-retries=0
autoconnect-priority=100
wait-device-timeout=90000

[ipv4]
method=auto
may-fail=false
dhcp-timeout=2147483647
dns=172.30.0.14;172.30.0.15
dns-search=rtc-kit.cloud.nexign.com;cloud.nexign.com;billing.ru;net.billing.ru
ignore-auto-dns=true

[ipv6]
method=disabled
```

This will ignore the search suffix coming from openstack neutron DHCP agents.

But, нowever, I have my doubts that this is the core issue.

There is the same issue: https://github.com/openshift/okd/issues/272 but the assumption was about etcd timeouts, нow can I look deeper to find the cause?

**Comment by vrutkovs** [comment]
>Because of IPI there is no any DNS registration for nodes. Is it required?

The nodes should have FQDN hostnames (as they are now), but these should have `baseDomain` suffix.

>There is the same issue: #272 but the assumption was about etcd timeouts, нow can I look deeper to find the cause?

Checked `etcd` pod logs - few warning about transations taking > 100ms, but nothing major. etcd cluster didn't assemble however (due to unexpected node names) so this may backfire later

**Comment by ITD27M01** [comment]
@vrutkovs 
While this is hot, I'd like to get your attention. I've reproduced the issue with synced baseDomain and nodes fqdns:

https://drive.google.com/file/d/1QTb471NzzxQQfV4nzJXlB-1BRIB9nAUJ

**Comment by vrutkovs** [comment]
etcd still can't assemble the cluster - not sure why:
>embed: rejected connection from "10.100.0.183:58166" (error "remote error: tls: bad certificate", ServerName "")

because etcd has expects different IPs in `etcd-host-service-endpoints.yaml`:
```
- addresses:
  - hostname: etcd-bootstrap
    ip: 192.0.2.200
  - hostname: etcd-0
    ip: 192.0.2.2
  - hostname: etcd-1
    ip: 192.0.2.3
  - hostname: etcd-2
    ip: 192.0.2.4
```

Not sure where `192.x` is coming from - do the nodes get this address assigned from some other network? 
@mandre do you know where this IP might come from?

**Comment by ITD27M01** [comment]
@vrutkovs 
Thanks for your investigation. We are using OpenShiftSDN as you can see from install-config.yaml (ovnkubernrtes doesn't work at all). The services/nodes and pods networks are defined there. The ip's of nodes are coming from DHCP of the vxlan network created by the installer. The subnet is the same, as defined in config.

**Comment by vrutkovs** [comment]
Node ips are looking fine, I don't see 192.x being used anywhere except etcd-host

>The ip's of nodes are coming from DHCP of the vxlan network created by the installer.

That looks like a bug. Could you attach `.openshift-installer.log` if you have it handy?

**Comment by ITD27M01** [comment]
OK,  give me some time, I'll reproduce and attach.

**Comment by ITD27M01** [comment]
BTW the addresses are coming from bootkube.sh:

https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L103

And templates for manifests:

https://github.com/openshift/installer/blob/master/data/data/manifests/bootkube/etcd-host-service-endpoints.yaml.template#L12

**Comment by vrutkovs** [comment]
We're using `fcos` branch for OKD, but both replacements are [there](https://github.com/openshift/installer/blob/fcos/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L137) [as well](https://github.com/openshift/installer/blob/fcos/data/data/manifests/bootkube/etcd-host-service-endpoints.yaml.template#L12)

I'll rename the issue to reflect the findings

**Comment by ITD27M01** [comment]
These addresses are present on older releases which work well. Maybe it is expected?

**Comment by vrutkovs** [comment]
>These addresses are present on older releases which work well. Maybe it is expected?

It appears so, but I can't find any mention of this limitation.

Could you reconfigure the internal network to use 192.168.x.x and try again? I wonder if its the reason for the issue or simply a red herring

**Comment by ITD27M01** [comment]
Is it machineNetwork cidr? I doubt that the exact addresses successfully hit the targets from templates because DHCP will select them randomly.

**Comment by ITD27M01** [comment]
This command [1] generates the following:

```
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
```

[1]
```
./openshift-install create install-config
```

The tests for AWS should fail as well I think?
