### ISSUE TITLE
oVirt 4.4.1 - High performance master VMs setup without USB support but seem to configure USB devices

### ISSUE THREAD

**Issue by Klaas-** [openshift/okd#304]
**Describe the bug**

setting up a cluster with oVirt 4.4.1 creates an error:
`VM okd-pp9q6-master-0 is down with error. Exit message: unsupported configuration: Can't add USB input device. USB bus is disabled.`

I can get the high performance VMs to start if I enable USB support in settings or enable the VM headless setting.

**Version**

openshift-install-linux-4.5.0-0.okd-2020-08-12-020541.tar.gz
oVirt: 4.4.1.10-1.el8 // EL 8.2 Hypervisor

**How reproducible**

```
[user@hostname ~]# ./tmp/openshift-install create cluster --dir ./tmp/
[...]
INFO Creating infrastructure resources...
ERROR
ERROR Error: timeout while waiting for state to become 'up' (last state: 'down', timeout: 10m0s)
ERROR
ERROR   on ../tmp/openshift-install-197381732/masters/main.tf line 1, in resource "ovirt_vm" "master":
ERROR    1: resource "ovirt_vm" "master" {
ERROR
ERROR
[...]
```
Two tries both create the same outcome

**Log bundle**

There is no oc active yet. Error during master creation.

**Comment by vap0rtranz** [comment]
4.4.x Beta installers had the ability to customize VM Templates.  There had been a doc about the process -- basically download the qcow, import into oVirt, change as needed, specify the Template name for the installer to use -- but that has since been removed:

https://docs.openshift.com/container-platform/4.4/installing/installing_rhv/installing-rhv-creating-custom-vm.html

Evidently the 4.5.x installer no longer has this customization?? :(

**Comment by vrutkovs** [comment]
See [ovirt-specific customizations](https://github.com/openshift/installer/blob/fcos/docs/user/ovirt/customization.md) and [custom OS image](https://github.com/openshift/installer/blob/fcos/docs/dev/openstack/customization.md) (its for openstack, but applies to every provider)

**Comment by jamesarems** [comment]
```
apiVersion: v1
baseDomain: example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: 
    ovirt:
      vmType: server
      osDisk:
        sizeGB: 120
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    ovirt:
      vmType: server
      osDisk:
        sizeGB: 120
  replicas: 3
metadata:
  creationTimestamp: null
  name: okd
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
imageContentSources:
- mirrors:
  - docker.example.com/openshift/okd
  source: quay.io/openshift/okd
- mirrors:
  - docker.example.com/openshift/okd
  source: quay.io/openshift/okd-content
platform:
  ovirt:
    api_vip: 192.168.99.66
    dns_vip: 192.168.99.68
    ingress_vip: 192.168.99.67
    ovirt_cluster_id: 3839602c-cfd2-11ea-9e02-00163e05ca79
    ovirt_network_name: ovirtmgmt
    ovirt_storage_domain_id: 562c3c2f-b6dd-4266-96ef-57163cdad261
    vnicProfileID: 0000000a-000a-000a-000a-000000000398
publish: External
pullSecret: ''
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI45b6ljzMFIsHleuLDIc474xDY8LkgFhq14HPCgUti9cneGQFePJ74vpoiUkxy/YxhX/DH4BMLcYFW4i/+vqLaWo6BbwxgCthqTbTGl7ewqIkssPJKbvTmeE9UDYZJIvhB2sB5NS3pBpXfNXK4um/BdOLW/bh98q1PA1xcT2AEloZDD19AD3mFjKZL3jS9zAFyVfbs5JQ4qI8Rzmoz8flX1tyafG48If5/TNGjn1lmlDhyCTl+FTWzM7cG1r6dgg6+i5iN/hduY4vVLf0hGDkiovNZ3ehhyDTIIyVzozrVyqVMmF3hig241HRbSbR3+klzpWKz+Q8xwPvHwxVA6XD
```
