### ISSUE TITLE
cluster logging deployment does not allow viewing captured audit logs in Kibana

### ISSUE THREAD

**Issue by brianotte** [openshift/okd#318]
Installed cluster logging as directed from this URL:   https://docs.okd.io/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying.

In OKD deployment -- the audit.log locations on masters exists in both locations:
- /var/log/kube-apiserver
- /var/log/openshift-apiserver

Here is modified step 5b ( clo-instance.yaml ) that should only collect audit logs from https://docs.okd.io/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying  (NOTE:  I tried a default clo-instance.yaml -- and app, infra, audit logs sent to elasticsearch -- see below examples -- but index not create-able in Kibana) :

cat step_5b_clo-instance.yaml
```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      audit:
        maxAge: 21d
    elasticsearch:
      nodeCount: 3
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      storage:
        storageClassName: "gp2"
        size: 512G
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      replicas: 1
  curation:
    type: "curator"
    curator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      schedule: "30 3 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
```

**Describe the bug**
Audit logs got to Elasticsearch but cannot add index in Kibana.

**Version**
Server Version: 4.5.0-0.okd-2020-08-12-020541
AWS Installer Provisioned Infrastructure.

**How reproducible**
100%

**Log bundle**
Please let me know if needed (some or all -- and I can provide) -- but it is a large file:

du -s -h ./must-gather.local.1265493575915701287/
2.8G	./must-gather.local.1265493575915701287/

Please let me know if more information is needed.

Thank you for your help.

Brian
