### ISSUE TITLE
Network policies related to ingress doesn't work well 

### ISSUE THREAD

**Issue by behnm** [openshift/okd#329]
I have multi tenant environment and need to isolate my tenants at Network layer. 
I've defined 3 network policies:
1. 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector: null

2.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
  - Ingress

3. 
apiVersion: networking.k8s.io/v1  
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
spec:  
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
****
Also because of my ingress controller which is NetworkHost, _default_ namespace has been added the below label
**network.openshift.io/policy-group: ingress**
 
However, the traffic could not be recieved by  container. when I deleted the policies, all the things worked well , again.

**Comment by vrutkovs** [comment]
Please attach/link the [necessary info](https://docs.okd.io/latest/support/gathering-cluster-data.html)

**Comment by behnm** [comment]
which part of command "oc adm must-gather" could be helpfull?

**Comment by behnm** [comment]
> 
> 
> Please attach/link the [necessary info](https://docs.okd.io/latest/support/gathering-cluster-data.html)

**Comment by behnm** [comment]
> 
> 
> Please attach/link the [necessary info](https://docs.okd.io/latest/support/gathering-cluster-data.html)

which part of command "oc adm must-gather" could be helpfull?

**Comment by vrutkovs** [comment]
>which part of command "oc adm must-gather" could be helpfull?

Please link to a full must-gather

**Comment by behnm** [comment]
The full must-gather file is a large file (around 4.5GB) and its hard to share it. 
Could you guide me to send smaller files ?

**Comment by behnm** [comment]
http://185.147.160.55:8080/logs/

**Comment by vrutkovs** [comment]
You're running 4.5.0-0.okd-2020-08-12-020541, which is month old. Is the bug reproducible on latest version - 4.5.0-0.okd-2020-09-04-180756?

>I've defined 3 network policies:

Which namespace is that? Could you attach the output of `oc get networkpolicies`?

> my ingress controller which is NetworkHost, default namespace has been added

Ingress controller is running in `openshift-ingress` namespace

**Comment by behnm** [comment]
> 
> 
> You're running 4.5.0-0.okd-2020-08-12-020541, which is month old. Is the bug reproducible on latest version - 4.5.0-0.okd-2020-09-04-180756?
> 
-I will update the cluster to 80756. could it resolve the issue ?
> 
> Which namespace is that? Could you attach the output of `oc get networkpolicies`?

Behnam namspaces. 
the output of oc get networkpolicies

**allow-from-openshift-ingress      <none>         3d14h
allow-from-openshift-monitoring   <none>         2d23h
allow-same-namespace              <none>         2d23h**

> Ingress controller is running in `openshift-ingress` namespace

Yes.its correct. However base on the below link, I added the appropriate label for default namespace. The label is existed for `openshift-ingress` namespace.

https://docs.openshift.com/container-platform/4.1/networking/configuring-networkpolicy.html

""

_Determine if your default Ingress Controller uses the HostNetwork endpoint publishing strategy:

$ oc get --namespace openshift-ingress-operator ingresscontrollers/default \
  --output jsonpath='{.status.endpointPublishingStrategy.type}'_

""
What solution could be used? Just update the cluster?

**Comment by vrutkovs** [comment]
>I added the appropriate label for default namespace

Why? There are no pods there

>What solution could be used?

It would be nice to ensure it still happens on latest version, but its not guaranteed of course.

Please attach the networkpolicies you've created and your test procedure results

**Comment by pflaeging** [comment]
In my environments (Openshift 4.3 and OKD 4.5) these 3 configs are working:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-ingress
spec:
  podSelector:
    matchLabels:
      pflaeging.net/networkrole: ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
    - ports:
        - protocol: TCP
  policyTypes:
    - Ingress
```

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-monitoring
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: monitoring
    - ports:
      - protocol: TCP
  policyTypes:
    - Ingress
```

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-in-namespace
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  policyTypes:
    - Ingress
```

I've added `spec.ingress.ports.protocol=TCP` to make it work. It's not mentioned in the doc, but after trial and error it's working.
We've added a required label: `pflaeging.net/networkrole=ingress` for all pods with ingress traffic to support additional auditing. If you don't want this, kick the part out ;-).
