### ISSUE TITLE
Missing User RoleBindings in the Project Access Web UI

### ISSUE THREAD

**Issue by burkhat** [openshift/okd#346]
**Describe the bug**

We've one RoleBinding for a project admin which includes two users.
Via the CLI we can see the two users if you describe the rolebinding.

_"[root@amu1123 ~]# oc describe rolebinding gitops-user-binding
Name:         gitops-user-binding
Labels:       argocd.argoproj.io/instance=ns-dev-c2-0eu1-
Annotations:  Role:
  Kind:       ClusterRole
  Name:       admin
Subjects:
  Kind  Name      Namespace
  User  GRESS
  User  HERRNB_F"_

But in the Web UI only the first user is displayed. (Developer -> Project -> Project Access)
![image](https://user-images.githubusercontent.com/35066347/95084017-96c6f780-071d-11eb-8fa9-fa45853cd088.png)

If you search for RoleBindings two RoleBindings will be displayed:
![image](https://user-images.githubusercontent.com/35066347/95084185-d097fe00-071d-11eb-8edd-0d649818f72c.png)

Also If you delete the RoleBinding from the Project Access Web UI the complete RoleBinding will be deleted not only the first User will be removed

**Version**

4.5.0-0.okd-2020-10-03-012432 - UPI

**How reproducible**

Just create a RoleBinding which contains two users.

```
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: gitops-user-binding
roleRef:
  name: admin
subjects:
- kind: User
  name: GRESS
- kind: User
  name: HERRNB_F
userNames:
- GRESS
- HERRNB_F
```

**Log bundle**
