### ISSUE TITLE
Install ClusterLogging possible on OKD 4.5? Installation fails

### ISSUE THREAD

**Issue by acidwars** [openshift/okd#350]
**Describe the bug**
I try to install the Cluster Logging Operator on a OKD 4.5 installation with **no RedHat Registry Token** configured. 

As I can't see the Operator in the OperatorHub, I've tried to follow this guide https://docs.okd.io/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying. It ends up with this error message when I try to deploy "ClusterLogging":
```error: unable to recognize "03-logging.yaml": no matches for kind "ClusterLogging" in version "logging.openshift.io/v1"```

**Version**
OKD version release: 4.5.0-0.okd-2020-10-03-012432 UPI 

**How reproducible**
Follow this guide https://docs.okd.io/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying

I know from other OCP installations, that I can easily install the ClusterLogging Operator from the Hub. As this is not visible in OKD I assume that the operator is just not available for OKD. Can someone confirm that? But why is it mentioned in the docs?

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "elasticsearch-operator"
  namespace: "openshift-operators-redhat"
spec:
  channel: "4.6"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "elasticsearch-operator"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  targetNamespaces:
    - openshift-logging
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: "4.6"
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 1d
      infra:
        maxAge: 7d
      audit:
        maxAge: 7d
    elasticsearch:
      nodeCount: 3
      storage:
        storageClassName: "rook-ceph-block"
        size: 200G
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  curation:
    type: "curator"
    curator:
      schedule: "30 3 * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
```
