### ISSUE TITLE
[libvirt IPI] openshift-install error in machine-controller: flag provided but not defined: -leader-elect

### ISSUE THREAD

**Issue by marshallford** [openshift/okd#366]
**Describe the bug**

Installer does not spin up worker nodes, I suspect that some crucial workloads (like ingress?) need to be scheduled on a worker and that is why the installer is failing.

Snippet from `./openshift-install create cluster --dir=fog --log-level debug`:

```
failed to initialize the cluster: Working towards 4.5.0-0.okd-2020-10-22-163350: 86% complete, waiting on authentication, console, image-registry, kube-storage-version-migrator, monitoring
```

After the installer bombs out the only pod that isn't in a running or completed state is `machine-api-controllers-<ID>` in the namespace `openshift-machine-api`. The container that is crashing is `machine-controller` with the error `flag provided but not defined: -leader-elect`.

```
# install-config.yaml
apiVersion: v1
baseDomain: openshift.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 1
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: fog
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.126.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  libvirt:
    URI: qemu+tcp://some-dns-name/system
    network:
      if: openshift_fog0
publish: External
pullSecret: '{"auths":{"foobar.com":{"auth":"foobar"}}}'
sshKey: |
```

**Version**

Extracted from `registry.svc.ci.openshift.org/origin/4.5:libvirt-installer`.

```
./openshift-install unreleased-master-3198-g63200c80c431b8dbaa06c0cc13282d819bd7e5f8-dirty
built from commit 63200c80c431b8dbaa06c0cc13282d819bd7e5f8
release image registry.svc.ci.openshift.org/origin/release:4.5
```

**How reproducible**

Installer inconsistently fails during the bootstrap stage so hard to say.

**Log bundle**

TBD: Need to get approval before uploading.
