### ISSUE TITLE
azurerm_storage_blob.rhcos_image: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating Blob

### ISSUE THREAD

**Issue by brianotte** [openshift/okd#371]
**Describe the bug**
When installing into an AZURE private network space, openshift-install fails with the following error:

`time="2020-11-04T14:47:56-05:00" level=debug msg="2020/11/04 14:47:56 [DEBUG] azurerm_storage_blob.rhcos_image: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating Blob \"rhcosk1vi6.vhd\" (Container \"vhd\" / Account \"clusterk1vi6\"): Error opening source file for upload \"https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201004.3.0/x86_64/fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz\":open https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201004.3.0/x86_64/fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz: no such file or directory"`

I have tested getting that image with curl and wget (so direct connect connectivity works):

...from the system that is running openshift-install:

**TESTING curl**
[zaphod@beeblebrox scripts]# curl -o fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201004.3.0/x86_64/fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  526M  100  526M    0     0  27.1M      0  0:00:19  0:00:19 --:--:-- 23.0M

**TESTING wget**
[zaphod@beeblebrox scripts]# wget https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201004.3.0/x86_64/fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz
--2020-11-04 16:06:14--  https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201004.3.0/x86_64/fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz
Resolving builds.coreos.fedoraproject.org (builds.coreos.fedoraproject.org)... 99.86.230.128, 99.86.230.75, 99.86.230.86, ...
Connecting to builds.coreos.fedoraproject.org (builds.coreos.fedoraproject.org)|99.86.230.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 552118248 (527M) [application/x-xz]
Saving to: ‘fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz.1’

100%[=======================================================================================================================================================================>] 552,118,248  139MB/s   in 3.9s

2020-11-04 16:06:18 (134 MB/s) - ‘fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz.1’ saved [552118248/552118248]

**CONFIRMATION FILES EXIST FROM curl AND wget**
[zaphod@beeblebrox scripts]# ls -al | grep xz
-rw-r--r--. 1 root root 552118248 Nov  4 16:06 fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz
-rw-r--r--. 1 root root 552118248 Oct 19 14:56 fedora-coreos-32.20201004.3.0-azure.x86_64.vhd.xz.1
-->

- Both work -- but openshift-install errors getting image.  
- I have tried multiple OKD 4.6 versions.  
- This is most recent and have additional trace logging if that will help.

**Version**

**IPI install method attempted.**

**./openshift-install version**
./openshift-install 4.6.0-0.okd-2020-11-04-104427
built from commit c3816ca357a337d3396345d8c69b19fbde219884
release image registry.svc.ci.openshift.org/origin/release@sha256:6f55c950a7b66e85481f6cdd64e835965b6019e292f621c2558923e9bba126a7

**How reproducible**

**100% reproducible.**

**Log bundle**

Did not get oc adm must-gather as cluster did not install.  

Here is install-config-yaml used:
```
apiVersion: v1
baseDomain: beeblebrox.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:
      osDisk:
        diskSizeGB: 512
      type: Standard_E4s_v3
      zones:
      - "1"
      - "2"
      - "3"
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  architecture: amd64
  name: master
  platform:
    azure:
      type: Standard_D4s_v3
      osDisk:
        diskSizeGB: 1024
      zones:
      - "1"
      - "2"
      - "3"
  replicas: 3
metadata:
  creationTimestamp: null
  name: zaphod
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: {REDACTED}-POC-USEAST2
    networkResourceGroupName: {REDACTED}-POC-USEAST2
    virtualNetwork: {REDACTED}-USEAST2-VNET
    controlPlaneSubnet: {REDACTED}-OCP-SNET
    computeSubnet: {REDACTED}-OCP-SNET
    region: eastus2
    outboundType: UserDefinedRouting
publish: Internal
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"{REDACTED}","email":"zaphod@beeblebrox.com"},"quay.io":{"auth":"{REDACTED}","email":"zaphod@beeblebrox.com"},"registry.connect.redhat.com":{"auth":"{REDACTED}","email":"zaphod@beeblebrox.com"},"registry.redhat.io":{"auth":"{REDACTED}","email":"zaphod@beeblebrox.com"}}}'
sshKey: |
  ssh-rsa {REDACTED}
```
