### ISSUE TITLE
Ingress cannot resolve cluster.local addresses

### ISSUE THREAD

**Issue by berndkuennen** [openshift/okd#375]
**Describe the bug**

Hello everybody,

we've setup an ingress which is basically working. But on path /fonts we route to a service in a parallel namespace, which is referenced by a local service with "ExternalName". Both services (local & remote) are accessible when called from "standard" pods within the cluster.

While working on ICP, it's not on OKD which delivers just a HTTP 503. Investigations showed that the router pods in namespace openshift-ingress are using the external DNS servers, not the cluster DNS, so it cannot resolve *.cluster.local addresses.

Is this a bug, a "design feature" (if so, why?) or is this configurable?

Thanks in advance.

**Version**

4.5.0-0.okd-2020-10-03-012432, running on Vmware 

**How reproducible**

Example conf. snippet, symbolic, not complete:
```
...
# ingress in namespace-a :
spec:
  rules:
  - host: some.host.name
    http:
      paths:
      - backend:
          serviceName: main-app
          servicePort: http
        path: /
      - backend:
          serviceName: external-fonts
          servicePort: http
        path: /fonts/
 
---
# "foreign" service
apiVersion: v1
kind: Service
metadata:
  name: external-fonts
spec:
  type: ExternalName
  externalName: fonts-app.namespace-b.svc.cluster.local
  ports:
-   port: 8080
```

**Log bundle**

**Comment by vrutkovs** [comment]
Router doesn't use Ingresses, it parses Routes.

Is there a Route object there? Could you paste it here?

**Comment by berndkuennen** [comment]
Thank you for asking. Here're the relevant parts of the router object for the path /fonts/ :
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: main-app-name
    meta.helm.sh/release-namespace: namespace-a
  labels:
    app: main-app-name
    app.kubernetes.io/managed-by: Helm
    manager: openshift-controller-manager
  name: main-app-name-8mxzm
  namespace: namespace-a
spec:
  host: some.host.name
  path: /fonts/
  tls:
    key: ...
    certificate: ...
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: external-fonts
    weight: 100
  wildcardPolicy: None
```

The routing object for "/" is working fine and looks the same, except that the target service is using ClusterIP and not ExternalName.

**Comment by berndkuennen** [comment]
Hi there,

I did some further testing and added an experimental service to my namespace:
```
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: ExternalName
  externalName: some.other.host
```
The following values for some.other.host  have been tested:
- www.google.com : works
- some.intranet.host.mycompany.org : works
- fonts-app.namespace-b.svc.cluster.local : fails with http/503  (cluster internal routing)
- fonts-app.ext.dns.mycompany.org : fails with http/503   (cluster external routing)

I expected at least that the external app name would be working, but it doesn't. Could this be something due to TCP routing?

**Comment by VGerris** [comment]
For me none of the hosts types worked, not external or internal. I ended up using an EndPointSlice ( externalName does not seem to work AT ALL ). 
In there, the label pointing to the service is the service one can refer to ( it does not have to exist, it seems to be created by the label). For your case I think it looks something like :+1: 

```
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: slice-it
  namespace: namespace-a
  labels:
    kubernetes.io/service-name: test-service
addressType: FQDN
ports:
  - name: 'http'
    appProtocol: http
    protocol: TCP
    port: 8080
  - name: 'http1'
    appProtocol: http
    protocol: TCP
    port: 8081
endpoints:
  - addresses:
      - "servicename-in-b.namespace_b.svc"
    conditions:
      ready: true
```

This gives you the option to create a route in namespace A that points to the service in namespace B by using the servicename test-service.

I hope this helps, there may be better ways but this worked for me.
