### ISSUE TITLE
Azure openshift-install contacting public IP with the following set .platform.azure.publish: Internal

### ISSUE THREAD

**Issue by brianotte** [openshift/okd#388]
**Describe the bug**

1. The openshift-install creates 3 masters and 1 bootstrap node (and other stuff) in the resource group as expected.
2. The 3 masters report _Creation complete after ~10:41 seconds._
3. PROBLEM:  Concerning the bootstrap node -- openshift-install times out and fails with the following message:

```
...
DEBUG module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m10s elapsed]
DEBUG module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m20s elapsed]
DEBUG module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m30s elapsed]
DEBUG module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m40s elapsed]
ERROR
ERROR Error: Error waiting for creation of Linux Virtual Machine "${REDACTED}-bt6zw-bootstrap" (Resource Group "${REDACTED}-bt6zw-rg"): Code="OSProvisioningTimedOut" Message="OS Provisioning for VM '${REDACTED}-bt6zw-bootstrap' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. Also, make sure the image has been properly prepared (generalized).\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/ \r\n * If you are deploying more than 20 Virtual Machines concurrently, consider moving your custom image to shared image gallery. Please refer to https://aka.ms/movetosig for the same."
ERROR
ERROR   on ../../tmp/openshift-install-750899121/bootstrap/main.tf line 175, in resource "azurerm_linux_virtual_machine" "bootstrap":
ERROR  175: resource "azurerm_linux_virtual_machine" "bootstrap" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```
The RETURN_CODE from the openshift-install binary is:  1

NOTE:  The same install-config.yaml, when installing Openshift 4.6.1 works.

**Version**

```
./openshift-install version
./openshift-install 4.6.0-0.okd-2020-11-24-050344
built from commit 7b5bd8be9e5f18cc9b8af5f95d629ddd64c015cc
release image registry.svc.ci.openshift.org/origin/release@sha256:c9328862f07fee53cb8498db57ea7f17772cfb9eaa1fd18efc504bf8737beeb3
```

**How reproducible**

100% in Azure install.  When openshift-install is attempting to contact cluster, a netstat -an indicates the following:

```
tcp        0	  0 ${SYSTEMS_IP_RUNNING_openshift-install}:56612        ${PUBLIC_IP}:443        ESTABLISHED
```

It is believed that NO public IP should be created when attempting to install into a private Azure cluster -- but that is not known.

**Log bundle**

Can provide any log bundle in any log level -- as requested.

The end result is that openshift-install does not install into Azure private network

**Comment by brianotte** [comment]
NOTE:  The install-config.yaml contains the following segment:
```
platform:
  azure:
    baseDomainResourceGroupName: ${REDACTED}
    networkResourceGroupName: ${REDACTED}
    virtualNetwork: ${REDACTED}
    controlPlaneSubnet: ${REDACTED}
    computeSubnet: ${REDACTED}
    region: ${REDACTED}
    outboundType: UserDefinedRouting
publish: Internal
```

**Comment by vrutkovs** [comment]
>Can provide any log bundle in any log level -- as requested.

Please do

**Comment by brianotte** [comment]
I will work towards providing the .openshift_install.log in DEBUG logging level.  And determine if any other forensic information can be captured.

**Comment by brianotte** [comment]
While capturing an openshift-install with debug logging the following log segment JUMPED out at me:

```
time="2020-11-25T16:48:34-05:00" level=debug msg="module.vnet.azurerm_lb.public: Creating..."
time="2020-11-25T16:48:35-05:00" level=debug msg="module.vnet.azurerm_lb.public: Creation complete after 1s [id=/subscriptions/${REDACTED}/resourceGroups/${REDACTED}-bmznk-rg/providers/Microsoft.Network/loadBalancers/${REDACTED}-bmznk]"
```

Should that occur if this exists in the install-config.yaml ?
```
platform:
  azure:
    baseDomainResourceGroupName: ${REDACTED}
    networkResourceGroupName: ${REDACTED}
    virtualNetwork: ${REDACTED}
    controlPlaneSubnet: ${REDACTED}
    computeSubnet: ${REDACTED}
    region: ${REDACTED}
    outboundType: UserDefinedRouting
publish: Internal
```

I am just waiting for the current openshift-install to timeout... and will upload complete log.

**Comment by brianotte** [comment]
Here is the .openshift_install.log file for a failed install.  NOTE:  3 masters are successfully created.  The openshift-installer is attempting to contact the bootstrap machine on a public IP -- but the install-config.yaml file indicates to Publish: Internal

[scrubbed.openshift_install.log](https://github.com/openshift/okd/files/5599533/scrubbed.openshift_install.log)

Please let me know if there is more information that I can capture.

Thank you very much.

**Comment by brianotte** [comment]
Attempted OKD install into Private network with newly released 4.6.0-0.okd-2020-11-27-200126.  Here are the identified differences:

1. openshift-install attempts to query network on Azure private network IP.  Previous installs attempted to install into Azure private network, but the openshift-install binary would attempt to confirm bootstrap status on public IP.
2. Bootstrap instance, 3 masters, and 3 workers are created.  Previous installs did not create workers.

Here is a tail of the .openshift-install.log
```
time="2020-11-30T07:52:01-05:00" level=debug msg="module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m10s elapsed]"
time="2020-11-30T07:52:11-05:00" level=debug msg="module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m20s elapsed]"
time="2020-11-30T07:52:21-05:00" level=debug msg="module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m30s elapsed]"
time="2020-11-30T07:52:31-05:00" level=debug msg="module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m40s elapsed]"
time="2020-11-30T07:52:41-05:00" level=debug msg="module.bootstrap.azurerm_linux_virtual_machine.bootstrap: Still creating... [40m50s elapsed]"
time="2020-11-30T07:52:48-05:00" level=error
time="2020-11-30T07:52:48-05:00" level=error msg="Error: Error waiting for creation of Linux Virtual Machine \"${REDACTED}-89wdj-bootstrap\" (Resource Group \"${REDACTED}-89wdj-rg\"): Code=\"OSProvisioningTimedOut\" Message=\"OS Provisioning for VM '${REDACTED}-89wdj-bootstrap' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later. Also, make sure the image has been properly prepared (generalized).\\r\\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \\r\\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/ \\r\\n * If you are deploying more than 20 Virtual Machines concurrently, consider moving your custom image to shared image gallery. Please refer to https://aka.ms/movetosig for the same.\""
```

Please let me know if I can provide more information -- as I am here to help.

Thank you.

**Comment by brianotte** [comment]
The exact same install-config.yaml used works with OpenShift Installer 4.6.4.

**Comment by brianotte** [comment]
Is there any additional logging that can be provided to help diagnose problems installing OKD 4.6.0-0.okd-2020-11-27-200126 into Azure Private network with the following settings?
```
platform:
  azure:
    baseDomainResourceGroupName: ${REDACTED}
    networkResourceGroupName: ${REDACTED}
    virtualNetwork: ${REDACTED}
    controlPlaneSubnet: ${REDACTED}
    computeSubnet: ${REDACTED}
    region: ${REDACTED}
    outboundType: UserDefinedRouting
publish: Internal
```
