### ISSUE TITLE
Azure IPI with cluster proxy builds 3 masters but does not find bootstrap complete

### ISSUE THREAD

**Issue by brianotte** [openshift/okd#404]
**Describe the bug**

- Azure IPI with cluster proxy setting builds 3 masters but does not find bootstrap complete, and times out at about 40 minutes.
- The Azure network is private.
- The same install-config.yaml with no proxy setting builds cluster to completion.

NOTE:  Red Hat Openshift works with proxy settings in install-config.yaml (same file).

**Version**

./openshift-install version
./openshift-install 4.6.0-0.okd-2020-11-27-200126
built from commit 7b5bd8be9e5f18cc9b8af5f95d629ddd64c015cc
release image quay.io/openshift/okd@sha256:a5392db432c990ee012ab189e9fa0d7b6a168f6e9b9e9da7fb10768b48752ca0

**How reproducible**

100% fails with proxy settings in install-config.yaml
100% works with NO proxy settings in install-config.yaml

**Log bundle**

Cluster does not install to provide.  Please let me know what logs I can provide.  I can ssh to bootstrap machine, it reboots about every 6 minutes -- and there are pods that are attempting to start and then restarting.  Not sure how to collect logs as openshift-install gather bootstrap only indicated that it could not connect -- even though I could ssh core@${BOOTSTRAP_IP} with no password (I tried every thinkable permutation related to --key= and even without).

Can go on and on -- but please let me know what is best information to help, and I will provide that.

Here is a snippet from the install-config
```
platform:
  azure:
    baseDomainResourceGroupName: ${REDACTED}
    networkResourceGroupName: ${REDACTED}
    virtualNetwork: ${REDACTED}
    controlPlaneSubnet: ${REDACTED}
    computeSubnet: ${REDACTED}
    region: ${REDACTED}
    outboundType: UserDefinedRouting
publish: Internal
```
