### ISSUE TITLE
The Ignition configuration lacks the configuration of http proxy

### ISSUE THREAD

**Issue by l30006821** [openshift/okd#436]
**Describe the bug**

**Version**

**How reproducible**

**Log bundle**

When I installed OKD4 on a restricted network, the Proxy was configured in the install-config.yaml file, but none of the configuration of the Proxy was found in the ign profile of the bootstrap that was generated.After bootstrap is started, the mirror cannot be pulled through proxy. The mirror can only be pulled when I export http_proxy and https_proxy. Is there anything wrong with my configuration? thank you 

my config files like this:
```
apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

proxy:
  httpProxy: test:test@proxy.com:8080
  httpsProxy: test:test@proxy.com:8080
  noProxy: 192.168.122.0/24,.lab.okd.local

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
```

the version is openshift-install 4.6.0-0.okd-2020-11-27-200126
