### ISSUE TITLE
Pod doesn't get ready if created using REST call with request format as "application/vnd.kubernetes.protobuf"

### ISSUE THREAD

**Issue by sawantshivaji1997** [openshift/okd#464]
**Describe the bug**
I am trying to create a Pod with REST call to the API server and request body has **application/vnd.kubernetes.protobuf** format. Pod message is first serialized and extra bytes are added at starting as specified [here](https://kubernetes.io/docs/reference/using-api/api-concepts/#protobuf-encoding). API server accepts the request and creates the Pod but the Pod doesn't get ready. Describing Pod shows the following warning
```
Warning FailedCreatePodSandBox 2m10s kubelet, ip-10-0-185-107.ap-south-1.compute.internal Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_pod1_test_c29f90dc-7cf4-49f2-81ff-c7edf93126a7_0(feca2744ef3885bd13fede3ecca34013a6ea37bd05aa0e649a83207137669664): Multus: [test/pod1]: error adding container to network "ovn-kubernetes": delegateAdd: error invoking confAdd - "ovn-k8s-cni-overlay": error in getting result from AddNetwork: CNI request failed with status 400: '[test/pod1] failed to get pod annotation: timed out waiting for the condition
```
I found a similar error [here](https://bugzilla.redhat.com/show_bug.cgi?id=1849728) but I didn't get much info from it.
Also, if the same request is made using JSON, it works without any issue and Pod comes up in running state.

**Version**
4.5.0-0.okd-2020-07-14-153706-ga.
Cluster is deployed on AWS using IPI method

**How reproducible**
100%

Providing Pod spec too.
```
apiVersion: v1
kind: Pod
metadata:
  name: Pod1
  namespace: test
spec:
  containers:
  - image: XYZ:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /echo
        port: 443
        scheme: HTTPS
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    name: container1
    ports:
    - containerPort: 443
      name: https
      protocol: TCP
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 22
      name: ssh
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /echo
        port: 443
        scheme: HTTPS
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: dockerregcred
  priority: 0
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
```
