### ISSUE TITLE
Ingress-controller defaultCertificate with cert-manager

### ISSUE THREAD

**Issue by Born2Bake** [openshift/okd#469]
Hi

**Describe the bug**

**Version**

ClusterIssuer:

```
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
type: Opaque
stringData:
  api-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: okd-dev
  namespace: openshift-ingress
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: xxxxxxxxxxxxxxxxxxxxxxxxx
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: okd-dev
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudflare:
          email: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          apiKeySecretRef:
            name: cloudflare-api-key
            namespace: cert-manager
            key: api-key
```

Certificate

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: okd-trbl-dev
  namespace: openshift-ingress
spec:
  secretName: okd-trbl-dev
  issuerRef:
    name: okd-dev
    kind: ClusterIssuer
  commonName: '*.apps.okd.xxx.com'
  dnsNames:
  - '*.apps.okd.xxx.com'
```

Certificate describe:

```
oc get cert
NAME           READY   SECRET         AGE
okd-trbl-dev   True    okd-trbl-dev   16m

Events:
  Type    Reason     Age   From          Message
  ----    ------     ----  ----          -------
  Normal  Issuing    16m   cert-manager  Issuing certificate as Secret does not exist
  Normal  Generated  16m   cert-manager  Stored new private key in temporary Secret resource "okd-trbl-dev-wn4s2"
  Normal  Requested  16m   cert-manager  Created new CertificateRequest resource "okd-trbl-dev-hkvs9"
  Normal  Issuing    16m   cert-manager  The certificate has been successfully issued
```

Result:

```
oc patch --type=merge --namespace openshift-ingress-operator ingresscontrollers/default   --patch '{"spec":{"defaultCertificate":{"name":"okd-trbl-dev"}}}'

bn@DESKTOP-IQ0K33P:~$ oc get po -n openshift-ingress
NAME                              READY   STATUS    RESTARTS   AGE
router-default-78595f8977-4v2nr   1/1     Running   0          11m
router-default-78595f8977-kzsv8   1/1     Running   0          14m
router-default-78595f8977-x5c6z   1/1     Running   0          12m

bn@DESKTOP-IQ0K33P:~$ oc get po -n openshift-console
NAME                        READY   STATUS    RESTARTS   AGE
console-5f455474-bv6lr      1/1     Running   0          14m
console-5f455474-rr8mb      1/1     Running   0          14m
downloads-687c66dc7-fjjk4   1/1     Running   0          5h24m
downloads-687c66dc7-qjhsx   1/1     Running   0          5h5m

bn@DESKTOP-IQ0K33P:~$ oc get po -n openshift-authentication
NAME                               READY   STATUS    RESTARTS   AGE
oauth-openshift-56c9f44b6c-lpqhl   1/1     Running   0          14m
oauth-openshift-56c9f44b6c-x98bc   1/1     Running   0          14m


oc get co
NAME                                       VERSION                         AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.6.0-0.okd-2021-01-17-185703   True        False         False      10m
cloud-credential                           4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
cluster-autoscaler                         4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
config-operator                            4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
console                                    4.6.0-0.okd-2021-01-17-185703   True        False         False      14m
csi-snapshot-controller                    4.6.0-0.okd-2021-01-17-185703   True        False         False      5h27m
dns                                        4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
etcd                                       4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
image-registry                             4.6.0-0.okd-2021-01-17-185703   True        False         False      5h3m
ingress                                    4.6.0-0.okd-2021-01-17-185703   True        False         False      3h23m
insights                                   4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
kube-apiserver                             4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
kube-controller-manager                    4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
kube-scheduler                             4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
kube-storage-version-migrator              4.6.0-0.okd-2021-01-17-185703   True        False         False      5h5m
machine-api                                4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
machine-approver                           4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
machine-config                             4.6.0-0.okd-2021-01-17-185703   True        False         False      5h1m
marketplace                                4.6.0-0.okd-2021-01-17-185703   True        False         False      5h13m
monitoring                                 4.6.0-0.okd-2021-01-17-185703   True        False         False      4h52m
network                                    4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
node-tuning                                4.6.0-0.okd-2021-01-17-185703   True        False         False      6h
openshift-apiserver                        4.6.0-0.okd-2021-01-17-185703   True        False         False      5h1m
openshift-controller-manager               4.6.0-0.okd-2021-01-17-185703   True        False         False      3d14h
openshift-samples                          4.6.0-0.okd-2021-01-17-185703   True        False         False      6h1m
operator-lifecycle-manager                 4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
operator-lifecycle-manager-catalog         4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
operator-lifecycle-manager-packageserver   4.6.0-0.okd-2021-01-17-185703   True        False         False      5h1m
service-ca                                 4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
storage                                    4.6.0-0.okd-2021-01-17-185703   True        False         False      4d8h
```

and finally, openshift-console logs:

```
2021-01-18T21:55:04Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.okd.xxx.com/oauth/token failed: Head https://oauth-openshift.apps.okd.xxx.com: x509: certificate is valid for oauth-openshift.openshift-authentication.svc, oauth-openshift.openshift-authentication.svc.cluster.local, not oauth-openshift.apps.okd.xxx.com
```

I am not sure if its surely a bug but would really appreciate if you can advice on that one.

Thank you
