### ISSUE TITLE
OKD 4.6+ : Documentation of NetworkPolicies is not correct

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#526]
Hi,

we use NetworkPolicies to allow selective access to our namespaces.

Beginning with OKD 4.6 the method described in the docs does not work anymore:
https://docs.openshift.com/container-platform/4.6/networking/network_policy/about-network-policy.html

To get NetworkPolicies working you must set 
```
...
    - ports:
        - protocol: TCP
...
```

An example NetworkPolicy that works should look like this:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-ingress
spec:
  podSelector:
    matchLabels:
      pflaeging.net/networkrole: ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
    - ports:
        - protocol: TCP
  policyTypes:
    - Ingress
```

We use OVNKubernetes network plugin. Before OKD 4.6 we used OpenShiftSDN. I don't know if this change is related to that or not.

Do other users see that also?

Greetings,

Josef

**Comment by mburke5678** [comment]
@jomeier Thank you for your input. 

I am not expert with networking. The docs show a Network Policy example that includes `ports.protocol: tcp` when you want to  only allow HTTP and HTTPS traffic. Are you suggesting all Network policies require `ports.protocol: tcp`?

**Comment by jomeier** [comment]
@mburke5678 
> @jomeier Thank you for your input.
> 
> I am not expert with networking. The docs show a Network Policy example that includes `ports.protocol: tcp` when you want to only allow HTTP and HTTPS traffic. Are you suggesting all Network policies require `ports.protocol: tcp`?

Yes that's the only way it works for us (at least with OVNKubernetes).

**Comment by danwinship** [comment]
That policy doesn't say what you think it does. It says "allow from any namespace labeled `network.openshift.io/policy-group: ingress`, and _also_ allow anything that is TCP". In other words, the reason it fixed things for you is because you are now allowing all traffic.

Note that the "allow from policy group ingress" policy only has any effect at all if you have ingress controllers running with the nodeport or loadbalancer publishing strategy; if ingress is using the hostnetwork publishing strategy, then ingress traffic will be coming from a host-network pod and so it can't be matched by a namespace-based NetworkPolicy (and there is no good way to match it via any NetworkPolicy). This is something that is being addressed in 4.8. (https://github.com/openshift/enhancements/pull/561)

Anyway, I'm guessing that your problem is that something caused your ingress configuration to change from one of the pod-network-based strategies to the host-network-based strategy.

**Comment by pflaeging** [comment]
> Hi,
> 
> we use NetworkPolicies to allow selective access to our namespaces.
> 
> Beginning with OKD 4.6 the method described in the docs does not work anymore:
> https://docs.openshift.com/container-platform/4.6/networking/network_policy/about-network-policy.html
> 
> To get NetworkPolicies working you must set
> 
> ```
> ...
>     - ports:
>         - protocol: TCP
> ...
> ```
> 
> An example NetworkPolicy that works should look like this:
> 
> ```
> kind: NetworkPolicy
> apiVersion: networking.k8s.io/v1
> metadata:
>   name: allow-from-ingress
> spec:
>   podSelector:
>     matchLabels:
>       pflaeging.net/networkrole: ingress
>   ingress:
>     - from:
>         - namespaceSelector:
>             matchLabels:
>               network.openshift.io/policy-group: ingress
>     - ports:
>         - protocol: TCP
>   policyTypes:
>     - Ingress
> ```
> 
> We use OVNKubernetes network plugin. Before OKD 4.6 we used OpenShiftSDN. I don't know if this change is related to that or not.
> 
> Do other users see that also?
> 
> Greetings,
> 
> Josef

There's one little small bug in the networkpolicy: please remove the `-` in front of port:

Though the definition should be:
```yaml
spec:
  podSelector:
    matchLabels:
      pflaeging.net/networkrole: ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
    ports:
    - protocol: TCP 
  policyTypes:
  - Ingress
```

That was my bug in the original posting:

- in the first form you will allow everything from namespaces `ingress` OR all TCP ports (means nearly everything)
- in the second form you will allow everything from namespace `ingress` with TCP ports (thats the right definition at least for me ;-))

Sorry, it was my buggy posting long time ago, ...
