### ISSUE TITLE
NetworkManager is requesting multiple IP addresses over DHCP for bridges with strange MACs ?

### ISSUE THREAD

**Issue by jomeier** [openshift/okd#540]
Hi,

we found a problem that made us crazy today but it explains a lot effects we saw in the last days:

**OKD 4.6 - OVNKubernetes on vSphere UPI: DHCP enabled**

We had the problem, that sometimes after reboots of some of the masters the API server was not reachable. This morning we rebooted another master and the cluster was completely down. After a reboot of one of the masters the API was back again.

What happened?

We sshed in one of the masters and saw that ETCD was unhealthy. We checked the members and found out, that one of the members IP addresses did not belong to one of the three masters.

A colleague looked in the logs of our companie's DHCP server and saw, that the master VMs that we rebooted made a DHCP request with alternating MAC addresses on each reboot. The DHCP server served two alternating IP addresses to the VM, and ETCD got unhealthy. Also OVNKubernetes Masters weren't able to start because they also tried to connect to the faulty IP address.

It seems that not only the ens192 network interface requests an IP address from the DHCP server but also some bridges(?). Maybe it is a race condition in NetworkManager.

Because promiscuous mode is enabled in our vSphere network the "false" MAC address is not discarded.

Do you have any ideas how we can overcome this problem? It regularly breaks our clusters.

Thanks and greetings,

Josef

**Comment by philipp1992** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1852106
https://bugzilla.redhat.com/show_bug.cgi?id=1853750
 seems to be this issue

**Comment by vrutkovs** [comment]
We don't use NM from RHEL, could you file a Fedora bug for that?

**Comment by jomeier** [comment]
https://github.com/coreos/fedora-coreos-tracker/issues/757

**Comment by jomeier** [comment]
The solution seems to be to write this file to all nodes:

```
 # sudo vi /etc/systemd/network/98-ovs-mac.link
 [Match]
 Driver=openvswitch

 [Link]
```

https://bugzilla.redhat.com/show_bug.cgi?id=1936961

You can mitigate the problem by applying this MachineConfigs:

Workers:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 00-worker-fix-random-mac-issue
spec:
  config:
    ignition:
      config:
        replace:
          verification: {}
      proxy: {}
      security:
        tls: {}
      timeouts: {}
      version: 3.1.0
    passwd: {}
    storage:
      files:
        - contents:
            source: >-
              data:text/plain;charset=utf-8;base64,W01hdGNoXQpEcml2ZXI9b3BlbnZzd2l0Y2gKW0xpbmtdCk1BQ0FkZHJlc3NQb2xpY3k9bm9uZQ==
            verification: {}
          group: {}
          mode: 384
          overwrite: true
          path: /etc/systemd/network/98-ovs-mac.link
          user:
            name: root
    systemd: {}
  fips: false
  kernelArguments: null
  kernelType: ''
  osImageURL: ''
```

Masters:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-fix-random-mac-issue
spec:
  config:
    ignition:
      config:
        replace:
          verification: {}
      proxy: {}
      security:
        tls: {}
      timeouts: {}
      version: 3.1.0
    passwd: {}
    storage:
      files:
        - contents:
            source: >-
              data:text/plain;charset=utf-8;base64,W01hdGNoXQpEcml2ZXI9b3BlbnZzd2l0Y2gKW0xpbmtdCk1BQ0FkZHJlc3NQb2xpY3k9bm9uZQ==
            verification: {}
          group: {}
          mode: 384
          overwrite: true
          path: /etc/systemd/network/98-ovs-mac.link
          user:
            name: root
    systemd: {}
  fips: false
  kernelArguments: null
  kernelType: ''
  osImageURL: ''
```
