### ISSUE TITLE
 vSphere: Bootstrap Server Failures, Bootstrap Cluster No Nodes

### ISSUE THREAD

**Issue by klzsysy** [openshift/okd#59]
hi:

I try install okd4 in vsphere, but failure -_-

## configure:

- okd version: 4.4.0-0.okd-2020-01-31-123546 [link](https://origin-release.svc.ci.openshift.org/releasestream/4.4.0-0.okd/release/4.4.0-0.okd-2020-01-31-123546)
- CoreOS version: 31.20200127.20
- vsphere version: 6.7u3
- install-config.yaml

```yaml
apiVersion: v1
## The base domain of the cluster. All DNS records will be sub-domains of this base and will also include the cluster name.
baseDomain: ifaii.lo
compute:
- name: worker
  replicas: 3
  hyperthreading: Enabled
controlPlane:
  name: master
  hyperthreading: Enabled
  replicas: 3
metadata:
  ## The name for the cluster
  name: openshift4
networking:
  clusterNetworks:
  - cidr: 172.31.0.0/22
    hostPrefix: 25
  # machineCIDR: 10.30.40.0/24
  # networkType: OpenShiftSDN
  serviceNetwork:
  - 172.31.128.0/22
platform:
  vsphere:
    ## The hostname or IP address of the vCenter
    vcenter: vcenter.ifaii.lo
    ## The name of the user for accessing the vCenter
    username: administrator@vsphere.local
    ## The password associated with the user
    password: xxx
    ## The datacenter in the vCenter
    datacenter: home
    ## The default datastore to use.
    defaultDatastore: NVME-SSD
## The pull secret that provides components in the cluster access to images for OpenShift components.
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"xxx==","email":"klzsysy@gmail.com"},"quay.io":{"auth":"xxx==","email":"klzsysy@gmail.com"},"registry.connect.redhat.com":{"auth":"xxx==","email":"klzsysy@gmail.com"},"registry.redhat.io":{"auth":"xxx==","email":"klzsysy@gmail.com"}}}'

## The default SSH key that will be programmed for `core` user.
sshKey: "ssh-rsa AAAAB3...... sonny@Sonny.macmini"
```
- dhcp config
    ![image](https://user-images.githubusercontent.com/3226923/73558292-d43bfc80-448d-11ea-82b7-a71465064545.png)
- haproxy
```
frontend openshift-api-server
    bind *:6443
    default_backend openshift-api-server
    mode tcp
    option tcplog

backend openshift-api-server
    balance source
    mode tcp
    server btstrap 172.30.40.16:6443 check
    server master1 172.30.40.11:6443 check
    server master2 172.30.40.12:6443 check
    server master3 172.30.40.13:6443 check

frontend machine-config-server
    bind *:22623
    default_backend machine-config-server
    mode tcp
    option tcplog

backend machine-config-server
    balance source
    mode tcp
    server btstrap 172.30.40.16:22623 check
    server master1 172.30.40.11:22623 check
    server master2 172.30.40.12:22623 check
    server master3 172.30.40.13:22623 check

frontend ingress-http
    bind *:80
    default_backend ingress-http
    mode tcp
    option tcplog

backend ingress-http
    balance source
    mode tcp
    server worker1 172.30.40.14:80 check
    server worker2 172.30.40.15:80 check

frontend ingress-https
    bind *:443
    default_backend ingress-https
    mode tcp
    option tcplog

backend ingress-https
    balance source
    mode tcp
    server worker1 172.30.40.14:443 check
    server worker2 172.30.40.15:443 check
```

## error info
```sh
[root@bootstrap kubernetes]# podman container list
CONTAINER ID  IMAGE                                                                                                                               COMMAND               CREATED        STATUS            PORTS  NAMES
a7e40d31e38f  registry.svc.ci.openshift.org/origin/4.4-2020-01-31-123546@sha256:e4fca6e7d9d2df952886ad9d8296a04713996fa42355addb675f52dbd522b421  start --tear-down...  3 minutes ago  Up 3 minutes ago         blissful_mcnulty
```

```sh
[root@bootstrap kubernetes]# journalctl -b -f -u bootkube.service
-- Logs begin at Fri 2020-01-31 16:20:38 UTC. --
1月 31 17:00:15 bootstrap.openshift4.ifaii.lo bootkube.sh[777]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
1月 31 17:00:15 bootstrap.openshift4.ifaii.lo bootkube.sh[777]: [#5760] failed to create some manifests:
1月 31 17:00:15 bootstrap.openshift4.ifaii.lo bootkube.sh[777]: "99_openshift-machineconfig_99-master-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-master-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
1月 31 17:00:15 bootstrap.openshift4.ifaii.lo bootkube.sh[777]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
```

```sh
[root@bootstrap kubernetes]# cd /etc/kubernetes/
[root@bootstrap kubernetes]# ls
bootstrap-configs  bootstrap-manifests  bootstrap-secrets  cloud  kubeconfig  kubelet-plugins  manifests  static-pod-resources
[root@bootstrap kubernetes]# oc --kubeconfig=kubeconfig get pod -A
NAMESPACE                                               NAME                                                              READY   STATUS    RESTARTS   AGE
openshift-apiserver-operator                            openshift-apiserver-operator-6664b744c-2sq6h                      0/1     Pending   0          23m
openshift-authentication-operator                       authentication-operator-78cc975698-ckqjh                          0/1     Pending   0          22m
openshift-cloud-credential-operator                     cloud-credential-operator-6f6fc564bc-6jljc                        0/1     Pending   0          23m
openshift-cluster-machine-approver                      machine-approver-fd785f4cf-4rjhh                                  0/2     Pending   0          23m
openshift-cluster-node-tuning-operator                  cluster-node-tuning-operator-6768657597-vsk6k                     0/1     Pending   0          23m
openshift-cluster-version                               cluster-version-operator-66c759476f-txzg8                         0/1     Pending   0          23m
openshift-controller-manager-operator                   openshift-controller-manager-operator-559c5874b-4xkmt             0/1     Pending   0          23m
openshift-csi-snapshot-controller-operator              csi-snapshot-controller-operator-7fbdc4fff7-7brtj                 0/1     Pending   0          22m
openshift-dns-operator                                  dns-operator-6dd45d9469-kkkcx                                     0/2     Pending   0          23m
openshift-etcd-operator                                 etcd-operator-b58f99c47-fldtb                                     0/1     Pending   0          22m
openshift-insights                                      insights-operator-789b886fd-wzjts                                 0/1     Pending   0          23m
openshift-kube-apiserver-operator                       kube-apiserver-operator-89fd96878-6fcrg                           0/1     Pending   0          23m
openshift-kube-controller-manager-operator              kube-controller-manager-operator-66d6db7d86-m8zt9                 0/1     Pending   0          23m
openshift-kube-scheduler-operator                       openshift-kube-scheduler-operator-6c5b896b6b-45jk5                0/1     Pending   0          23m
openshift-kube-storage-version-migrator-operator        kube-storage-version-migrator-operator-8bb456fdf-69pqp            0/1     Pending   0          23m
openshift-machine-api                                   machine-api-operator-5cf48f8d85-n9blv                             0/2     Pending   0          22m
openshift-machine-config-operator                       machine-config-operator-7b4495f948-pdwbk                          0/1     Pending   0          23m
openshift-network-operator                              network-operator-76d8cf58bd-g75f9                                 0/1     Pending   0          23m
openshift-operator-lifecycle-manager                    catalog-operator-654747c7f4-xb9b9                                 0/1     Pending   0          23m
openshift-operator-lifecycle-manager                    olm-operator-878bf5744-zzj4n                                      0/1     Pending   0          23m
openshift-service-ca-operator                           service-ca-operator-79497bc6dd-7j7r8                              0/1     Pending   0          23m
openshift-service-catalog-apiserver-operator            openshift-service-catalog-apiserver-operator-55975f64f7-tb2hd     0/1     Pending   0          23m
openshift-service-catalog-controller-manager-operator   openshift-service-catalog-controller-manager-operator-78855rglp   0/1     Pending   0          23m
openshift-support                                       support-operator-8589547564-cd2vg                                 0/1     Pending   0          23m
[root@bootstrap kubernetes]# oc --kubeconfig=kubeconfig -n openshift-apiserver-operator get po
NAME                                           READY   STATUS    RESTARTS   AGE
openshift-apiserver-operator-6664b744c-2sq6h   0/1     Pending   0          23m
[root@bootstrap kubernetes]# oc --kubeconfig=kubeconfig -n openshift-apiserver-operator describe pod openshift-apiserver-operator-6664b744c-2sq6h
Name:                 openshift-apiserver-operator-6664b744c-2sq6h
Namespace:            openshift-apiserver-operator
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               app=openshift-apiserver-operator
                      pod-template-hash=6664b744c
Annotations:          <none>
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/openshift-apiserver-operator-6664b744c
Containers:
  openshift-apiserver-operator:
    Image:      registry.svc.ci.openshift.org/origin/4.4-2020-01-31-123546@sha256:3818d95df2f4c461956d9416b5536a39c2299735fc1706f151f778fc4e4ba053
    Port:       8443/TCP
    Host Port:  0/TCP
    Command:
      cluster-openshift-apiserver-operator
      operator
    Args:
      --config=/var/run/configmaps/config/config.yaml
    Requests:
      cpu:     10m
      memory:  50Mi
    Environment:
      IMAGE:                   registry.svc.ci.openshift.org/origin/4.4-2020-01-31-123546@sha256:c2c536716124ba127114cb022d9bb74cffb522d4ce9358051df9e18a94d6ca46
      OPERATOR_IMAGE:          registry.svc.ci.openshift.org/origin/4.4-2020-01-31-123546@sha256:3818d95df2f4c461956d9416b5536a39c2299735fc1706f151f778fc4e4ba053
      OPERATOR_IMAGE_VERSION:  4.4.0-0.okd-2020-01-31-123546
      OPERAND_IMAGE_VERSION:   4.4.0-0.okd-2020-01-31-123546
    Mounts:
      /var/run/configmaps/config from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from openshift-apiserver-operator-token-tjrhb (ro)
      /var/run/secrets/serving-cert from serving-cert (rw)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  openshift-apiserver-operator-serving-cert
    Optional:    true
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      openshift-apiserver-operator-config
    Optional:  false
  openshift-apiserver-operator-token-tjrhb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  openshift-apiserver-operator-token-tjrhb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 120s
                 node.kubernetes.io/unreachable:NoExecute for 120s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  no nodes available to schedule pods
  Warning  FailedScheduling  <unknown>  default-scheduler  no nodes available to schedule pods
  Warning  FailedScheduling  <unknown>  default-scheduler  no nodes available to schedule pods
[root@bootstrap kubernetes]# oc --kubeconfig=kubeconfig get node
No resources found in default namespace.
[root@bootstrap kubernetes]# oc --kubeconfig=kubeconfig get csr -A
No resources found
[root@bootstrap kubernetes]#
```

why bootstrap cluster No nodes 

I need to provide more information?
