### ISSUE TITLE
More than 80% of v4 subnets available to assign to the nodes are allocated. Current v4 subnet allocation percentage is 87.5

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#594]
I think this is not a bug, but after we installed our OKD-Cluster (version 4.7.0-0.okd-2021-03-21-094146, bare metal) with 3 master and 11 worker, the following alert will be trigged: 
More than 80% of v4 subnets available to assign to the nodes are allocated. Current v4 subnet allocation percentage is 87.5 (V4SubnetAllocationThresholdExceeded)

The hole expression of the rule "ovnkube_master_allocated_v4_host_subnets / ovnkube_master_num_v4_host_subnets * 100 > 80" shows a value of 87.5

ovnkube_master_num_v4_host_subnets shows "32" and ovnkube_master_allocated_v4_host_subnets shows "28"

We used the following network configuration in the install-config.yaml
```
networking:
  clusterNetwork:
  - cidr: 10.200.0.0/16
    hostPrefix: 21
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
```
Do you have some idea what is going wrong here or what must be adjusted there that we do not see this error?
