### ISSUE TITLE
baremetal upi fails to install with hotfix

### ISSUE THREAD

**Issue by RobVerduijn** [openshift/okd#601]
Hello,

I'm trying to install okd on baremetal upi in a 3 master configuration 0 workers.
However it keeps failing to install the masters
I'm using
okd_version: 4.7.0-0.okd-2021-04-11-124433
fedora_coreos: 33.20210217.3.0

I got everything working with okd 4.6.0-0.okd-2021-01-23-132511 and fedcos 32.20201104.3.0 but the upgrade procedure adds many hours to the installation procedure which is why I'm trying to get things to work with the latest versions.

The bootstrap node is ok, it installs 33.20210217.3.0 then after a while it pivots and reboots into 33.20210328.3.0 and after some more time I can see on my loadbalancer it's listening for nodes to check in.

The master nodes however don't check in
Even if I apply the suggestion from the [dns and fcos workaround](https://github.com/openshift/okd/blob/master/Guides/UPI/baremetal/manual-dns-and-fcos-dns-fix.md)

The bootstrap node works fine with or without the workaround.
However the master nodes fail with and without the workaround.

The main giveaway of this error is loudly being flooded on the master nodes.
[::1]:53: read udp [::1]:60125->[::1]:53: read: connection refused

Strange thing is that the ignition file for the master looks identical with or without the workaround.
I guess I'm doing a silly typo in my okd-configure-master-node-dns.yaml file

My okd-configure-master-node-dns.yaml:
```
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: okd-configure-master-node-dns
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      links:
        - path: /etc/resolv.conf
          overwrite: true
          target: ../run/systemd/resolve/resolv.conf
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,W1Jlc29sdmVdCkROU1N0dWJMaXN0ZW5lcj1ubwo=
          mode: 420
          overwrite: true
          path: /etc/systemd/resolved.conf.d/50-no-dns-stub.conf
```
my master.ign (looks the same with or without the workaround)
```
{
    "ignition": {
        "config": {
            "merge": [
                {
                    "source": "https://api-int.okd.example.com:22623/config/master"
                }
            ]
        },
        "security": {
            "tls": {
                "certificateAuthorities": [
                    {
                        "source": "data:text/plain;charset=utf-8;base64,<my base64 encoded cert>"
                    }
                ]
            }
        },
        "version": "3.1.0"
    }
}
```

**Version**
okd_version: 4.7.0-0.okd-2021-04-11-124433
fedora_coreos: 33.20210217.3.0

**How reproducible**
install fedcos on the master and reboot it
(pxe install with static ip config in the pxe)
**Log bundle**
Sadly no use since I cannot login to the master nodes yet.
