### ISSUE TITLE
etcd failing to start, ingress & api servers in endless crash loop

### ISSUE THREAD

**Issue by jdbarnes-isi** [openshift/okd#628]
**Describe the bug**

When provisioning a single node deployment to test the okd version, etcd never gets started, and ingress and api servers are stuck in an endless crash loop.

My nodes are: boostrap, master.

**Version**

`4.7.0-0.okd-2021-04-24-103438` UPI install method.
This happened with FCOS 33.20210217.3.0 and 33.20210426.3.0. possibly for different reasons.
Attached is the error from 33.20210217.3.0, which is what our developers are using.

**How reproducible**

In my own minimal experience this appears to be stuck about 90-95% of the time. This deployment worked once in ~15 deployments and I did not change a thing.

**Log bundle**

[must-gather.local.7877003190763564014.tar.gz](https://github.com/openshift/okd/files/6444522/must-gather.local.7877003190763564014.tar.gz)

**Comment by vrutkovs** [comment]
>When provisioning a single node deployment to test the okd version

Are you sure you have:

```
compute:                                                                                            
- name: worker                                                                                      
  replicas: 0                                                                                       
controlPlane:                                                                                       
  name: master                                                                                      
  replicas: 1
```
in install-config.yaml? etcd is stuck waiting from three nodes, as it doesn't have necessary `useUnsupportedUnsafeNonHANonProductionUnstableEtcd: true` override in spec.

**Comment by jdbarnes-isi** [comment]
```
apiVersion: v1
baseDomain: portal.example.com
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
metadata:
  name: test
platform:
  none: {}
```
yeah :(
my test instance ignition files get generated by
```
rm -rf ign
mkdir ign
cp install-config.yaml ign/
openshift-install --dir ign create ignition-configs
```
I will go ahead and do this again manually and verify this to be sure.
