### ISSUE TITLE
Bootstrap not using mirror registry pullSecret in install-config.yaml

### ISSUE THREAD

**Issue by DizzyThermal** [openshift/okd#654]
**Describe the bug**

My mirror docker registry (for OKD4 content) shows that the bootstrap node is attempting to login with empty credentials - NOT the credentials I provided in the install-config.yaml under pullSecret.

(1) SSH to bootstrap node from installer/mirror node: `ssh core@bootstrap.okd4.example.com`
(2) Become root user: `sudo -i`
(3) Attempt to login to docker registry: `docker login services.okd4.example.com:5000`

```
Authenticating with existing credentials...
WARNING! Your password will be store unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#crendentials-store

Login Succeeded
```

This tells me that the pullSecret from install-config.yaml is making it's way to `/root/.docker/config.json` - which looks correct and matches the pullSecret.

docker.io/library/registry:2.7.1 pod logs (where my mirror OKD Quay.io content is stored) shows my successful connection, but also a slew of failed attempts from the bootstrap process:

```
ERROR[] error authenticating user "": authentication failure go.version=go1.11.2 http.request.host="services.okd4.example.com:5000" ....
```

**Version**

```
Version: 4.7.0-0.okd-2021-05-22-050008
UPI install - Bare Metal
```

Relevant portions of my install-config looks like this - can provide more pieces if necessary to debugging:

```
imageContentSources:
- mirrors:
  - services.okd4.example.com:5000/okd4
  source: quay.io/openshift/okd
- mirrors:
  - services.okd4.example.com:5000/okd4
  source: quay.io/openshift/okd-content

pullSecret: '{"auths":{"services.okd4.example.com:5000":{"auth": "base-64-encoded-username-and-password"}}}'
```

My additionalTrustBundle is also provided at the bottom, so the registry doesn't complain about an unknown certificate authority.

My overall question is, what is suppose to tell the bootstrap/installation process to use the credentials provided in the install-config.yaml.. I've come across a thread mentioning that if no proxy is configured, that the install process won't try to use mirror registries, but I don't know the validity of this claim.

This process worked for OKD 4.5.0-0.okd-2020-10-15-235428 when I tried it last.

Any logs I provide will need to be hand-typed because of our network restrictions - we're unable to download files/logs in our environment.

Thanks in advance for any help!
