### ISSUE TITLE
Bootstrap not using imageContentSources

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#66]
It seems that bootstrap is not following imageContentSources from install-config.yaml for its podman images. I am seeing `registry.svc.ci.openshift.org` as the pod being launched instead of my local quay registry which I had specified. 

Is this purely a label or is this the source of the image being pulled?
```
ce652a6ee3ce  registry.svc.ci.openshift.org/origin/4.4-2020-01-31-202523@sha256:001db6ee754695c5ef85966747e7a98fff4d80589f16db93d285c5189220cedb  serve --cacrt=/op...  2 hours ago    Up 2 hours ago           etcd-signer
```

Install Config:
```
imageContentSources:
- mirrors:
  - quay.example.net/okd/4.4.0-0.okd-2020-02-03-164031
  source: registry.svc.ci.openshift.org/origin/4.4-2020-02-03-164031
- mirrors:
  - quay.example.net/okd/4.4.0-0.okd-2020-02-03-164031
  source: registry.svc.ci.openshift.org/origin/release
```
