### ISSUE TITLE
systemd.unified_cgroup_hierarchy=0 kernel argument missing on new nodes

### ISSUE THREAD

**Issue by spasche** [openshift/okd#710]
**Describe the bug**

I deployed new nodes on a OKD cluster with user provisioned infrastructure using libvirt KVM virtual machines.
Cluster was at version 4.7.0-0.okd-2021-06-13-090745 when new nodes were added.
On the new nodes, we could see pods failing. For instance, BuildConfig pods were failing with the error:
```
error: failed to retrieve cgroup limits: cannot determine cgroup limits: open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory
```

After investigations, I noticed that the new nodes were missing the `systemd.unified_cgroup_hierarchy=0` kernel boot parameter, which exposes `/sys/fs/cgroup/memory/`.

rpm-ostree status on the new nodes:
```
rpm-ostree status
State: idle
Deployments:
● pivot://quay.io/openshift/okd-content@sha256:ce3e69194860476064a7a36075a9de3b46b2eaf6851ceedae41a69e5124a3637
              CustomOrigin: Managed by machine-config-operator
                   Version: 47.34.202106191111-0 (2021-06-19T11:14:24Z)

  pivot://quay.io/openshift/okd-content@sha256:ce3e69194860476064a7a36075a9de3b46b2eaf6851ceedae41a69e5124a3637
              CustomOrigin: Managed by machine-config-operator
                   Version: 47.34.202106191111-0 (2021-06-19T11:14:24Z)
```

As a workaround, I deployed the following MachineConfig:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-openshift-machineconfig-worker-kargs
spec:
  kernelArguments:
    - 'systemd.unified_cgroup_hierarchy=0'
```

**Version**

4.7.0-0.okd-2021-06-13-090745 when the new nodes were added.
User provisioned infrastructure using libvirt KVM virtual machines.
Cluster later updated to 4.7.0-0.okd-2021-06-19-191547 (which didn't fix the issue).

**How reproducible**

The same issue happened on the 5 nodes that were added.

**Log bundle**

I can't attach the link here for confidentiality reasons. I'll happily send the link by email.
