### ISSUE TITLE
Kibana couldn't find any Elasticsearch data anymore after a while (Red Hat OpenShift Logging Operator)

### ISSUE THREAD

**Issue by myg0v** [openshift/okd#713]
**Describe the bug**
After a while Kibana couldn't find any Elasticsearch data anymore. If I try to recreate the index pattern in the Kibana-UI at kibana-openshift-logging.apps.**/app/kibana (Management > Index Patterns > Create index pattern) it only return the following error:
```
Couldn't find any Elasticsearch data
You'll need to index some data into Elasticsearch before you can create an index pattern. Learn how or get started with some sample data sets.
```

The external fluentd forwarding is still working fine. I was able to create an index at the beginning (after I enabled and configured the Operators initially) but it stops working after some days after and I was not able to see any logs in Kibana anymore.

**Version**
OKD: 4.7.0-0.okd-2021-06-04-191031
Red Hat OpenShift Logging: 5.0.5-11
OpenShift Elasticsearch Operator: 5.0.4-21

**How reproducible**
I followed the instructions on https://docs.okd.io/latest/logging/cluster-logging-deploying.html and https://docs.okd.io/latest/logging/cluster-logging-external.html#cluster-logging-collector-log-forward-fluentd_cluster-logging-external to forward the logs to an external fluentd agent and forward also to the default outputRefs.

ClusterLogForwarder-instance yaml (Red Hat OpenShift Logging)
```
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  inputs:
    - application:
        namespaces:
          - ***-**
          - ***-**
          - ***-**
      name: my-app-logs
  outputs:
    - name: external-fluentd-target
      type: fluentdForward
      url: 'tcp://***-**.***.net:24224'
  pipelines:
    - inputRefs:
        - my-app-logs
      labels:
        clusterId: okd-test
      name: forward-to-external-fluentd-target
      outputRefs:
        - external-fluentd-target
    - inputRefs:
        - application
      labels:
        clusterId: okd-test
      name: internal-log
      outputRefs:
        - default
```

ClusterLogging-instance yaml (Red Hat OpenShift Logging)
```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    logs:
      fluentd:
        resources:
          limits:
            memory: 736Mi
          requests:
            cpu: 200m
            memory: 736Mi
      type: fluentd
  curation:
    curator:
      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
      schedule: 30 3 * * *
    type: curator
  logStore:
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: 200m
          memory: 16Gi
      storage:
        size: 200G
        storageClassName: ocs-storagecluster-ceph-rbd
    retentionPolicy:
      application:
        maxAge: 1d
      audit:
        maxAge: 7d
      infra:
        maxAge: 7d
    type: elasticsearch
  managementState: Managed
  visualization:
    kibana:
      proxy:
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      replicas: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
    type: kibana
```

**Log bundle**
must-gather bundle: https://drive.google.com/file/d/1XveaSDtJbLPn_dNiStAqWsud-SjJzDV9/view?usp=sharing
