### ISSUE TITLE
A long request to the dns server

### ISSUE THREAD

**Issue by ofedotov51** [openshift/okd#725]
There is a problem with a long request to the dns server. It is shown in the example below. The request is sent from the pod and the problem manifests itself from the pod. I tried to solve the problem by doing forwarding, but it didn't help.

```
curl -w "dns_resolution: %{time_namelookup}, tcp_established: %{time_connect}, ssl_handshake_done: %{time_appconnect}, TTFB: %{time_starttransfer}, time_redirect: %{time_redirect}, time_total: %{time_total}s\n" -o /dev/null -s https://ya.ru
dns_resolution: 5.073743, tcp_established: 5.087487, ssl_handshake_done: 5.103775, TTFB: 5.166707, time_redirect: 0.000000, time_total: 5.193673s
```
I attach an example of forwarding.

  ```
servers:  
   - name:
     zones:
       - *.ru
       - *.com
     forwardPlugin:
       upstreams:
         - dns1
         - dns2:5353
```
cluster version 4.5.0-0.okd-2020-10-15-235428
