### ISSUE TITLE
OIDC Authentication Provider Fails

### ISSUE THREAD

**Issue by jdhirst1** [openshift/okd#73]
Version: 4.4.0-0.okd-2020-02-04-174205

Since the recent update to openshift-authentication, oidc no longer works as expected. When configuring OIDC as an identity provider, the user is not redirected to the challenge server at all but is presented with a standard login form instead. If the user attempts to authenticate using this method, it fails.

Identity Provider: (my setup is using Keycloak)
```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: oidcidp 
    mappingMethod: claim 
    type: OpenID
    openID:
      clientID: kubernetes-cluster
      clientSecret: 
        name: oauth-secret
      claims: 
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
      issuer: https://sso.example.net/auth/realms/master
```

Can someone please try to reproduce this? I have confirmed that my Keycloak instance is available and has no issues with other applications, but I want to be sure that its not something I have done.
