### ISSUE TITLE
[OKD4.6+] LDAP idP works fine but shows User Name Strings only base64 encoded - Bug?

### ISSUE THREAD

**Issue by devzeronull** [openshift/okd#769]
Hi,

with some OKD version change (I think OKD 4.5 to 4.6 or so) Names of Users provided through LDAP idP which were automatically created after initial authentication get created with Usernames as base64 encoded string:

![grafik](https://user-images.githubusercontent.com/77630137/125784233-c56702e9-ef1d-40d8-b686-4b78b0e92b44.png)

We are sure that this was not like that in an pre 4.6 OKD Release and is also not in our 3.11 clusters...

Our idP configuration works fine ever since and has never changed from our sides:
```
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - Email
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: uid=XXX,dc=XXX,dc=XX
      bindPassword:
        name: ldaps-secret
      ca:
        name: ldaps-ca
      insecure: false
      url: ldaps://XXX.XXX:636/dc=XXX,dc=XX?uid??(memberOf=cn=XXX,ou=XXX,dc=XXX,dc=XX)
    mappingMethod: claim
    name: ldaps
    type: LDAP
```

Do you have any clue how to have the names shown decoded?
This is really annoying, e.g. the base64 string appears in requester, creator fields and therefor also in logging and monitoring systems...
