### ISSUE TITLE
[OKD 4.4] Bootstrap machine fails to start on OpenStack (train)

### ISSUE THREAD

**Issue by devops-42** [openshift/okd#79]
OKD version: `openshift-install-linux-4.4.0-0.okd-2020-02-08-183312`
OpenStack version: `20.0.1-1.el7         @centos-openstack-train`

Hi,

when trying to install OKD 4.4 on OpenStack the installer starts to provision networks, security groups and spawns 3 master and 1 bootstrap VM. The masters came up, but the bootstrap aborted with an error. The `.openshift_install.log` shows:

```
time="2020-02-10T16:57:23+01:00" level=error msg="Warning: Quoted references are deprecated"
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=error msg="  on ../../tmp/openshift-install-133112777/topology/sg-master.tf line 38, in resource \"openstack_networking_secgroup_rule_v2\" \"master_ingress_icmp\":"
time="2020-02-10T16:57:23+01:00" level=error msg="  38:   depends_on = [\"openstack_networking_secgroup_rule_v2.master_mcs\"]"
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=error msg="In this context, references are expected literally rather than in quotes."
time="2020-02-10T16:57:23+01:00" level=error msg="Terraform 0.11 and earlier required quotes, but quoted references are now"
time="2020-02-10T16:57:23+01:00" level=error msg="deprecated and will be removed in a future version of Terraform. Remove the"
time="2020-02-10T16:57:23+01:00" level=error msg="quotes surrounding this reference to silence this warning."
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=error msg="(and 44 more similar warnings elsewhere)"
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=error msg="Error: Error waiting for instance (67dd33cb-d68b-4f46-aa3b-f408f66cd936) to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)"
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=error msg="  on ../../tmp/openshift-install-133112777/bootstrap/main.tf line 31, in resource \"openstack_compute_instance_v2\" \"bootstrap\":"
time="2020-02-10T16:57:23+01:00" level=error msg="  31: resource \"openstack_compute_instance_v2\" \"bootstrap\" {"
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=error
time="2020-02-10T16:57:23+01:00" level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```

OpenStack shows an error like: 

```
2020-02-10 16:57:16.585 6188 WARNING nova.scheduler.utils [req-3979b98f-3cff-4bbe-bb80-165010a1cd25 0fac32856a6641a5b89e482f72892122 f358533d559440659bdcf69d0ece62c4 - default default] [instance: 67dd33cb-d68b-4f46-aa3b-f408f66cd936] Setting instance to ERROR state.: MaxRetriesExceeded: Exceeded maximum number of retries. Exhausted all hosts available for retrying build failures for instance 67dd33cb-d68b-4f46-aa3b-f408f66cd936.
```

The according project in OpenStack has an external network and a floating IP assigned which works for other VMs I tried to spawn manually. Resources are sufficient, as 3 masters are running. The same error will be thrown even if I try with one master only.

The installation config file I used:

```
apiVersion: v1
baseDomain: example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: okd4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    cloud: shiftstack
    computeFlavor: m1.special
    externalDNS: null
    externalNetwork: external_network
    lbFloatingIP: [IP_FROM_EXTERNAL_RANGE]
    octaviaSupport: "1"
    region: ""
publish: External
pullSecret: [REDACTED]
sshKey: |
  [REDACTED]
```

The flavor `m1.special` means: 4 vCPU, 8 GB RAM, 20 GB storage.

Googling around does not help, there were too less installation examples for OKD 4 on OpenStack. Does one have installed OKD on OpenStack successfully and can provide the installation/configuration steps?

Cheers and thanks!
