### ISSUE TITLE
[OKD4.7] Install FCOS 34 kernel headers from kernel-devel via machine-config like in RHCOS

### ISSUE THREAD

**Issue by devzeronull** [openshift/okd#842]
Hi,

is there a working way to install Fedora CoreOS Kernel-headers through a machineconfig in OKD?

The method as suggested with Red Hat CoreOS from OpenShift, described in https://github.com/falcosecurity/falco/issues/1505, by deploying it with a machine config like:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-extensions
spec:
  extensions:
    - kernel-devel
```
and
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: master-extensions
spec:
  extensions:
    - kernel-devel
```
doesn't seem to work, the MCO stucks degraded with missing packages:
> error running rpm-ostree install --allow-inactive kernel-devel: Checking out tree fb99ff5...doneEnabled rpm-md repositories: coreos-extensionsrpm-md repo 'coreos-extensions' (cached); generated: 2021-06-29T10:22:06ZImporting rpm-md...doneerror: Packages not found: kernel-devel: exit status 1

Any productive-ready idea despite building custom images would be appreciated :)

Best regards
