### ISSUE TITLE
OKD - 4.8.0-0.okd-2021-10-01-221835 missing libvirt support in the installer.

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#909]
Attempting to build Code Ready Containers for OKD 4.8.

4.8.0-0.okd-2021-10-01-221835

It appears as though libvirt support is missing from the installer.

```
./openshift-baremetal-install --dir crc-tmp-install-data create manifests

failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" file: platform: Invalid value: "libvirt": must specify one of the platforms (aws, azure, baremetal, gcp, kubevirt, none, openstack, ovirt, vsphere) 
```

Install Config:

```yaml
apiVersion: v1
baseDomain: testing
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform: {}
    replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: crc
networking:
  clusterNetwork:
    - cidr: 10.217.0.0/22
      hostPrefix: 23
  machineNetwork:
    - cidr: 192.168.126.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
    - 10.217.4.0/23
platform:
  libvirt:
    URI: qemu+tcp://192.168.122.1/system
    network:
      if: tt0
publish: External
pullSecret: |-
  {"auths":{"fake":{"auth": "Zm9vOmJhcgo="}}}
sshKey: ecdsa-sha2-nistp521 REDACTED== core
```
