### ISSUE TITLE
Bare-Metal UPI: Bootstrap not completing, restarting every 30 minutes

### ISSUE THREAD

**Issue by cgruver** [openshift/okd#97]
Release: 4.4.0-0.okd-2020-03-10-214705

The bootstrap node hangs at the repeating "MachineConfig" message for 30 minutes.

```
Mar 11 09:49:14 okd4-bootstrap bootkube.sh[749]: [#3542] failed to create some manifests:
Mar 11 09:49:14 okd4-bootstrap bootkube.sh[749]: "99_openshift-machineconfig_99-master-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-master-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
```

 After the bootstrap process times out and start again, the repeating "MachineConfig" error message continues for some time, then clears up and BootStrap continues.

The master nodes are stuck repeating the following:

```
Mar 11 10:29:31 okd4-master-0 systemd[1]: Starting Kubernetes Kubelet...
Mar 11 10:29:31 okd4-master-0 systemd[3351]: kubelet.service: Failed to execute command: No such file or directory
Mar 11 10:29:31 okd4-master-0 systemd[3351]: kubelet.service: Failed at step EXEC spawning /usr/bin/hyperkube: No such file or directory
Mar 11 10:29:31 okd4-master-0 systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Mar 11 10:29:31 okd4-master-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar 11 10:29:31 okd4-master-0 systemd[1]: Failed to start Kubernetes Kubelet.
Mar 11 10:29:41 okd4-master-0 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 140.
Mar 11 10:29:41 okd4-master-0 systemd[1]: Stopped Kubernetes Kubelet.
```

The bootstrap node is repeating:

```Mar 11 10:30:41 okd4-bootstrap bootkube.sh[21892]:         Pod Status:openshift-kube-scheduler/openshift-kube-scheduler        Ready
Mar 11 10:30:41 okd4-bootstrap bootkube.sh[21892]:         Pod Status:openshift-kube-controller-manager/kube-controller-manager        RunningNotReady
Mar 11 10:30:41 okd4-bootstrap bootkube.sh[21892]:         Pod Status:openshift-cluster-version/cluster-version-operator        Ready
Mar 11 10:30:41 okd4-bootstrap bootkube.sh[21892]:         Pod Status:openshift-kube-apiserver/kube-apiserver        RunningNotReady
```

Logs attached:

Before first bootstrap time-out:

[log-bundle-20200311055224.tar.gz](https://github.com/openshift/okd/files/4317618/log-bundle-20200311055224.tar.gz)

After first bootstrap time-out:

[log-bundle-20200311060004.tar.gz](https://github.com/openshift/okd/files/4317622/log-bundle-20200311060004.tar.gz)

After second bootstrap time-out:

[log-bundle-20200311061746.tar.gz](https://github.com/openshift/okd/files/4317627/log-bundle-20200311061746.tar.gz)

At this point, one master and one worker are available:
```
oc get nodes
NAME            STATUS   ROLES    AGE   VERSION
okd4-master-2   Ready    master   49m   v1.17.1
okd4-worker-0   Ready    worker   38m   v1.17.1

oc get csr
NAME        AGE   REQUESTOR                                                                   CONDITION
csr-dzkmp   39m   system:node:okd4-worker-0                                                   Approved,Issued
csr-jghzd   50m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-rr2b8   50m   system:node:okd4-master-2                                                   Approved,Issued
csr-wtgvs   39m   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
```

**Comment by vrutkovs** [comment]
>http: TLS handshake error from 10.11.11.100:48318: tls: client offered only unsupported versions: [300]

I think that was HAProxy misconfiguration last time, right?

**Comment by cgruver** [comment]
I did have config issues, but I think the TLS issue is new...  I have successfully deployed several times with different releases as they come available.  Although, I noticed that the bootstrap process would generally restart once before completing.


I am double checking the configs of HAProxy and DNS to make sure I didn't do anything silly.

Logs from other masters:

[10.11.11.102.zip](https://github.com/openshift/okd/files/4317909/10.11.11.102.zip)

[10.11.11.103.zip](https://github.com/openshift/okd/files/4317910/10.11.11.103.zip)

**Comment by cgruver** [comment]
HAProxy config and DNS config look good.  No changes across deployments.

One worker and one master successfully joined the cluster.  The others did not.

I'm going to destroy it and run it again.

**Comment by vrutkovs** [comment]
>Although, I noticed that the bootstrap process would generally restart once before completing.

Bootstrap node does reboot at least once.

>Error: error pulling image "registry.svc.ci.openshift.org/origin/4.4-2020-03-10-214705@sha256:25f60b2213fbda4ff2a7a550b91f5da8dd91096448df4f4702aa1fccda7c7703": unable to pull registry.svc.ci.openshift.org/origin/4.4-2020-03-10-214705@sha256:25f60b2213fbda4ff2a7a550b91f5da8dd91096448df4f4702aa1fccda7c7703: unable to pull image: Error writing blob: error storing blob to file "/var/tmp/storage871597621/3": read tcp 10.11.11.102:37054->74.125.21.128:443: read: connection reset by peer

Due to registry instability its recommended to use mirroring

**Comment by cgruver** [comment]
I will set up a mirror in my Nexus before the next run.

The Bootstrap node does reboot at the very beginning.  That's normal.  What I was seeing is the `bootkube.service` timing out and restarting itself.

**Comment by cgruver** [comment]
I have successfully created the mirror in my local Sonatype Nexus.  You were right about the registry instability...  I had to run the mirror several times to get all the images without some `500` errors.

I'll attempt the install from the mirror in the morning and update on progress.

If successful, I'll add it to the docs that I'm creating for this adventure.

**Comment by cgruver** [comment]
Update:  Successful Deployment, eventually...

   I observed similar behavior with the mirror.  The `bootkube.service` timed out spinning on:

```
Mar 12 12:18:10 okd4-bootstrap bootkube.sh[9271]: "99_openshift-machineconfig_99-worker-ssh.yaml": unable to get REST mapping for "99_openshift-machineconfig_99-worker-ssh.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1"
Mar 12 12:18:10 okd4-bootstrap bootkube.sh[9271]: [#686] failed to create some manifests:
```

After the timeout, it looped on that message for several more minutes, but did eventually complete.

```
Mar 12 12:28:02 okd4-bootstrap bootkube.sh[9271]: bootkube.service complete
Mar 12 12:28:02 okd4-bootstrap systemd[1]: bootkube.service: Succeeded.
Mar 12 12:28:02 okd4-bootstrap systemd[1]: bootkube.service: Consumed 14.348s CPU time.
```

```
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd4.oscluster.clgcom.org:6443... 
INFO API v1.17.1 up                               
INFO Waiting up to 40m0s for bootstrapping to complete... 
DEBUG Bootstrap status: complete                   
INFO It is now safe to remove the bootstrap resources 
```

Here's my current install-config.yaml:

```
apiVersion: v1
baseDomain: oscluster.clgcom.org
metadata:
  name: okd4
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.100.0.0/14 
    hostPrefix: 23 
  serviceNetwork: 
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 10.11.11.0/24
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
platform:
  none: {}
pullSecret: '{"auths": {"quay.io": {"auth": "Y2dydXZlc-ETC...", "email": ""},"nexus.oscluster.clgcom.org:5002": {"auth": "YW-ETC...", "email": ""}}}'
sshKey: ssh-rsa AAAAB3NzaC1... root@osc-controller01
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
 CERT_FROM_MY_NEXUS
  -----END CERTIFICATE-----
imageContentSources:
  - mirrors:
    - nexus.oscluster.clgcom.org:5002/origin
    source: registry.svc.ci.openshift.org/origin/4.4-2020-03-11-174228
  - mirrors:
    - nexus.oscluster.clgcom.org:5002/origin
    source: registry.svc.ci.openshift.org/origin/release
```

The log bundle is 45MB compressed...  So I just pulled logs from bootstrap and one master node.  If more are useful, I will attach.
[log-bundle-20200312084112.tar.gz](https://github.com/openshift/okd/files/4324178/log-bundle-20200312084112.tar.gz)
