### ISSUE TITLE
OKD 4.4 bootstrap hangs if manifests customized

### ISSUE THREAD

**Issue by stratus-ss** [openshift/okd#98]
**Problem Statement**: When editing the CVO or Ingress Controller manifests, the bootstrap hangs on reboot.

**Environment:** Libvirt using bare metal Fedora CoreOS initramfs and kernel image

**Technologies for Infrastructure:** DNSMasq, HAProxy, Firewalld, Apache 2.4.37, PXE Boot

**OpenShift Versions:** 
```
[root@gateway ignition]# openshift-install version
openshift-install 4.4.0-0.okd-2020-01-28-022517
built from commit 7ca0817244033e5f543541def5b18ea1bac440f7
release image registry.svc.ci.openshift.org/origin/release@sha256:2350fee6c0d8a980d499b7bbb3ba20137ffa58416bc1381304596772957f7836

[root@gateway ignition]# oc version
Client Version: 4.4.0-0.okd-2020-01-28-022517
```

**Fedora CoreOS Images:**
```
fedora-coreos-31.20200210.3.0-live-initramfs.x86_64.img 
fedora-coreos-31.20200210.3.0-live-kernel-x86_64
fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz
fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz.sig
```

Bootstrap hangs like this after the initial reboot:

![image](https://user-images.githubusercontent.com/8162705/76439629-0b59d380-6393-11ea-8542-15976c185811.png)

**Attempted updates:**

cvo manifest:
```
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  creationTimestamp: "2020-03-11T00:04:31Z"
  generation: 3
  name: version
  resourceVersion: "219704"
  selfLink: /apis/config.openshift.io/v1/clusterversions/version
  uid: 9e43c10d-9b3f-4f13-8a25-2e13f9b3ff34
spec:
  channel: stable-4.3
  clusterID: e8ed9a0e-a25c-45c0-a800-963fe9050774
  overrides:
  - group: apps/v1
    kind: Deployment
    name: etcd-quorum-guard
    namespace: openshift-machine-config-operator
    unmanaged: true
  upstream: https://api.openshift.com/api/upgrades_info/v1/graph
```

ingress operator

```
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: cluster
spec:
  domain: ${INGRESS_WILDCARD}
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: "true"
```

**Steps to reproduce:**

* download the oc client locally
*  run the extract command
```
oc adm release extract --tools registry.svc.ci.openshift.org/origin/release:4.4.0-0.okd-2020-01-28-022517
```
* make a unique dir and create the install-config.yaml
```
mkdir $(date %+F)
cd $(date %+F)

cat << EOF > install-config.yaml.bak
apiVersion: v1
baseDomain: ${BASE_DOMAIN}
compute:
- hyperthreading: Enabled  
  name: worker
  replicas: ${NUMBER_OF_WORKER_VMS}
controlPlane:
  hyperthreading: Enabled  
  name: master
  replicas: ${NUMBER_OF_MASTER_VMS}
metadata:
  name: ${CLUSTER_NAME}
networking:
  clusterNetwork:
  - cidr: ${CLUSTER_NETWORK}
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - ${SERVICE_NETWORK}
platform:
  none: {}
fips: false
pullSecret: ${PULL_SECRET}
sshKey: ${SSH_KEY}
EOF
```
* generate the manifests
```
openshift-install create manifests
```
* make edits
* create the ignition configs
```
 openshift-install create ignition-configs
```
* put the files in the apache directory
```
cp *.ign /var/www/html/ignition
```
* set the ownership and selinux contexts
```
chown -R apache. /var/www/html
restorecon -Rvv /var/www/html
```
* launch the vm and wait for it to hang.

I cannot run must-gather as the vm doesn't respond to SSH and hasn't started pulling pods or bringing up the API yet. 

I have tried first one manifest edit, then the other, then both at the same time. This issue is not present in OpenShift Container Platform 4.3. I have run the same process using documented process for OCP4.

In addition, with the exact same setup, simply running
```
openshift-install create ignition-configs
```
instead of even creating the manifests allows the bootstrap to install as expected
